// Generated by ReScript, PLEASE EDIT WITH CARE


let tag = "attack";

function Comp(T) {
  let addAttack = getWorldRect => ({
    id: tag,
    getWorldRect: getWorldRect
  });
  return {
    addAttack: addAttack
  };
}

let tagComponent = tag;

export {
  tag,
  tagComponent,
  Comp,
}
/* No side effect */
