// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as GameObjRaw$Kaplay from "@nojaf/rescript-kaplay/src/Components/GameObjRaw.res.mjs";

let tag = "attack";

function Comp(T) {
  let getClosestCorner = (attack, k, pokemonPosition) => {
    let attackRect = attack.getWorldRect();
    let attackCenter = attackRect.pos.add(k.vec2(attackRect.width / 2, attackRect.height / 2));
    let isAttackOnTheLeftOfPokemon = attackCenter.x < pokemonPosition.x;
    let isAttackOnTopOfPokemon = attackCenter.y < pokemonPosition.y;
    let leftX = attackRect.pos.x;
    let rightX = attackRect.pos.x + attackRect.width;
    let topY = attackRect.pos.y;
    let bottomY = attackRect.pos.y + attackRect.height;
    if (isAttackOnTheLeftOfPokemon) {
      if (isAttackOnTopOfPokemon) {
        return k.vec2(rightX, bottomY);
      } else {
        return k.vec2(rightX, topY);
      }
    } else if (isAttackOnTopOfPokemon) {
      return k.vec2(leftX, bottomY);
    } else {
      return k.vec2(leftX, topY);
    }
  };
  let addAttack = getWorldRect => ({
    id: tag,
    getWorldRect: getWorldRect
  });
  let addAttackWithTag = getWorldRectX => [
    addAttack(getWorldRectX),
    tag
  ];
  return {
    getClosestCorner: getClosestCorner,
    addAttack: addAttack,
    addAttackWithTag: addAttackWithTag
  };
}

GameObjRaw$Kaplay.Comp({});

function getClosestCorner(attack, k, pokemonPosition) {
  let attackRect = attack.getWorldRect();
  let attackCenter = attackRect.pos.add(k.vec2(attackRect.width / 2, attackRect.height / 2));
  let isAttackOnTheLeftOfPokemon = attackCenter.x < pokemonPosition.x;
  let isAttackOnTopOfPokemon = attackCenter.y < pokemonPosition.y;
  let leftX = attackRect.pos.x;
  let rightX = attackRect.pos.x + attackRect.width;
  let topY = attackRect.pos.y;
  let bottomY = attackRect.pos.y + attackRect.height;
  if (isAttackOnTheLeftOfPokemon) {
    if (isAttackOnTopOfPokemon) {
      return k.vec2(rightX, bottomY);
    } else {
      return k.vec2(rightX, topY);
    }
  } else if (isAttackOnTopOfPokemon) {
    return k.vec2(leftX, bottomY);
  } else {
    return k.vec2(leftX, topY);
  }
}

function addAttack(getWorldRect) {
  return {
    id: tag,
    getWorldRect: getWorldRect
  };
}

function addAttackWithTag(getWorldRectX) {
  return [
    addAttack(getWorldRectX),
    tag
  ];
}

function fromGameObj(obj) {
  if (obj.has(tag)) {
    return Primitive_option.some(obj);
  }
}

let Unit = {
  getClosestCorner: getClosestCorner,
  addAttack: addAttack,
  addAttackWithTag: addAttackWithTag,
  fromGameObj: fromGameObj
};

export {
  tag,
  Comp,
  Unit,
}
/*  Not a pure module */
