// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Z$Kaplay from "@nojaf/rescript-kaplay/src/Components/Z.res.mjs";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Pos$Kaplay from "@nojaf/rescript-kaplay/src/Components/Pos.res.mjs";
import * as Area$Kaplay from "@nojaf/rescript-kaplay/src/Components/Area.res.mjs";
import * as Math$Kaplay from "@nojaf/rescript-kaplay/src/Math.res.mjs";
import * as Move$Kaplay from "@nojaf/rescript-kaplay/src/Components/Move.res.mjs";
import * as Anchor$Kaplay from "@nojaf/rescript-kaplay/src/Components/Anchor.res.mjs";
import * as Sprite$Kaplay from "@nojaf/rescript-kaplay/src/Components/Sprite.res.mjs";
import * as Team$Skirmish from "../Team.res.mjs";
import * as Wall$Skirmish from "../Wall.res.mjs";
import * as Attack$Skirmish from "./Attack.res.mjs";
import * as Pokemon$Skirmish from "../Pokemon.res.mjs";
import * as GameObjRaw$Kaplay from "@nojaf/rescript-kaplay/src/Components/GameObjRaw.res.mjs";

GameObjRaw$Kaplay.Comp({});

Sprite$Kaplay.Comp({});

Pos$Kaplay.Comp({});

Move$Kaplay.Comp({});

Anchor$Kaplay.Comp({});

Z$Kaplay.Comp({});

Area$Kaplay.Comp({});

let include = Attack$Skirmish.Comp({});

let addAttackWithTag = include.addAttackWithTag;

let spriteName = "flame";

function load(k) {
  k.loadSprite(spriteName, "/sprites/moves/flame.png");
}

function cast(k, pokemon) {
  let pokemonWorldPos = pokemon.worldPos();
  let flame = k.add(Belt_Array.concatMany([
    [
      k.sprite(spriteName),
      k.pos(pokemonWorldPos),
      k.move(pokemon.direction, 120),
      k.z(-1),
      k.area(),
      pokemon.direction.y < 0 ? k.anchor("bot") : k.anchor("top"),
      Team$Skirmish.getTagComponent(pokemon.team)
    ],
    addAttackWithTag(function () {
      let flame = this ;
      return Math$Kaplay.Rect.makeWorld(k, flame.worldPos(), flame.width, flame.height);
    })
  ]));
  flame.onCollide(Pokemon$Skirmish.tag, (other, _collision) => {
    if (other.pokemonId !== pokemon.pokemonId) {
      console.log("Ember hit", other.pokemonId);
      other.hp = other.hp - 5 | 0;
      flame.destroy();
      return;
    }
  });
  flame.onCollide(Wall$Skirmish.tag, (param, _collision) => {
    flame.destroy();
  });
  k.wait(1, () => Pokemon$Skirmish.finishAttack(pokemon));
}

let move_cast = cast;

function move_addRulesForAI(param, param$1, param$2, param$3) {
  
}

let move = {
  id: 1,
  name: "Ember",
  maxPP: 25,
  baseDamage: 40,
  coolDownDuration: 1,
  cast: move_cast,
  addRulesForAI: move_addRulesForAI
};

let getClosestCorner = include.getClosestCorner;

let addAttack = include.addAttack;

let coolDown = 1;

export {
  getClosestCorner,
  addAttack,
  addAttackWithTag,
  spriteName,
  load,
  coolDown,
  cast,
  move,
}
/*  Not a pure module */
