// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Z$Kaplay from "@nojaf/rescript-kaplay/src/Components/Z.res.mjs";
import * as Pos$Kaplay from "@nojaf/rescript-kaplay/src/Components/Pos.res.mjs";
import * as Area$Kaplay from "@nojaf/rescript-kaplay/src/Components/Area.res.mjs";
import * as Math$Kaplay from "@nojaf/rescript-kaplay/src/Math.res.mjs";
import * as Move$Kaplay from "@nojaf/rescript-kaplay/src/Components/Move.res.mjs";
import * as Anchor$Kaplay from "@nojaf/rescript-kaplay/src/Components/Anchor.res.mjs";
import * as Sprite$Kaplay from "@nojaf/rescript-kaplay/src/Components/Sprite.res.mjs";
import * as Team$Skirmish from "../Team.res.mjs";
import * as Wall$Skirmish from "../Wall.res.mjs";
import * as Attack$Skirmish from "./Attack.res.mjs";
import * as Pokemon$Skirmish from "../Pokemon.res.mjs";
import * as GameObjRaw$Kaplay from "@nojaf/rescript-kaplay/src/Components/GameObjRaw.res.mjs";
import * as GameContext$Skirmish from "../GameContext.res.mjs";

GameObjRaw$Kaplay.Comp({});

Sprite$Kaplay.Comp({});

Pos$Kaplay.Comp({});

Move$Kaplay.Comp({});

Anchor$Kaplay.Comp({});

Z$Kaplay.Comp({});

Area$Kaplay.Comp({});

let include = Attack$Skirmish.Comp({});

let addAttack = include.addAttack;

let spriteName = "flame";

function load() {
  GameContext$Skirmish.k.loadSprite(spriteName, "/sprites/moves/flame.png");
}

function cast(pokemon) {
  let pokemonWorldPos = pokemon.worldPos();
  let flame = GameContext$Skirmish.k.add([
    GameContext$Skirmish.k.sprite(spriteName),
    GameContext$Skirmish.k.pos(pokemonWorldPos),
    GameContext$Skirmish.k.move(pokemon.direction, 120),
    GameContext$Skirmish.k.z(-1),
    GameContext$Skirmish.k.area(),
    pokemon.direction.y < 0 ? GameContext$Skirmish.k.anchor("bot") : GameContext$Skirmish.k.anchor("top"),
    Team$Skirmish.getTagComponent(pokemon.team)
  ]);
  flame.use(addAttack(() => Math$Kaplay.Rect.makeWorld(GameContext$Skirmish.k, flame.worldPos(), flame.width, flame.height)));
  pokemon.attackStatus = false;
  flame.onCollide(Pokemon$Skirmish.tag, (other, _collision) => {
    if (other.pokemonId !== pokemon.pokemonId) {
      console.log("Ember hit", other.pokemonId);
      other.hp = other.hp - 5 | 0;
      flame.destroy();
      return;
    }
  });
  flame.onCollide(Wall$Skirmish.tag, (param, _collision) => {
    flame.destroy();
  });
  GameContext$Skirmish.k.wait(1, () => {
    pokemon.attackStatus = true;
  });
}

let coolDown = 1;

export {
  addAttack,
  spriteName,
  load,
  coolDown,
  cast,
}
/*  Not a pure module */
