// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Math$Kaplay from "@nojaf/rescript-kaplay/src/Math.res.mjs";
import * as Shader$Kaplay from "@nojaf/rescript-kaplay/src/Components/Shader.res.mjs";
import * as Team$Skirmish from "../Team.res.mjs";
import * as Attack$Skirmish from "./Attack.res.mjs";
import * as Pokemon$Skirmish from "../Pokemon.res.mjs";
import * as TweenController$Kaplay from "@nojaf/rescript-kaplay/src/TweenController.res.mjs";
import * as KEventController$Kaplay from "@nojaf/rescript-kaplay/src/KEventController.res.mjs";
import Outline2pxFragraw from "../../shaders/outline2px.frag?raw";

let shaderName = "outline2px";

let outline2pxSource = Outline2pxFragraw;

function load(k) {
  k.loadShader(shaderName, undefined, outline2pxSource);
}

function cast(k, pokemon) {
  console.log("QuickAttack cast");
  pokemon.mobility = false;
  let pokemonWorldPos = pokemon.worldPos();
  let startY = pokemonWorldPos.y;
  let endY = startY - 30;
  let collisionCtrl = {
    contents: KEventController$Kaplay.empty
  };
  let tweenCtrl = {
    contents: TweenController$Kaplay.empty
  };
  let endAttack = () => {
    collisionCtrl.contents.cancel();
    tweenCtrl.contents.cancel();
    pokemon.mobility = true;
    pokemon.unuse(Shader$Kaplay.id);
    pokemon.unuse(Attack$Skirmish.id);
    pokemon.untag(Attack$Skirmish.tag);
  };
  collisionCtrl.contents = pokemon.onCollide(Team$Skirmish.opponent, (other, param) => {
    if (!other.is(Pokemon$Skirmish.tag)) {
      return;
    }
    other.hp = other.hp - 3 | 0;
    let pokemonPos = pokemon.worldPos();
    let otherPos = other.worldPos();
    let bounceDirection = pokemonPos.sub(otherPos).unit();
    pokemon.applyImpulse(bounceDirection.scale(90));
    other.applyImpulse(bounceDirection.scale(- 90));
    k.wait(0.15, () => {
      pokemon.vel = k.Vec2.ZERO;
      other.vel = k.Vec2.ZERO;
    });
    endAttack();
  });
  pokemon.use(k.shader(shaderName, () => ({
    u_resolution: k.vec2(pokemon.width, pokemon.height),
    u_color: k.Color.fromHex("#f0f9ff")
  })));
  pokemon.use(Attack$Skirmish.Unit.addAttack(function () {
    let pokemonWorldPos = pokemon.worldPos().add(- pokemon.halfSize, - pokemon.halfSize);
    return Math$Kaplay.Rect.makeWorld(k, pokemonWorldPos, pokemon.width, pokemon.height);
  }));
  pokemon.tag(Attack$Skirmish.tag);
  tweenCtrl.contents = k.tween(startY, endY, 0.4, value => {
    pokemon.worldPos(k.vec2(pokemonWorldPos.x, value));
  }, k.easings.easeOutElastic);
  tweenCtrl.contents.onEnd(endAttack);
}

let move_cast = cast;

function move_addRulesForAI(_k, _rs, _slot, _facts) {
  
}

let move = {
  id: 3,
  name: "Quick Attack",
  maxPP: 30,
  baseDamage: 40,
  coolDownDuration: 0.4,
  cast: move_cast,
  addRulesForAI: move_addRulesForAI
};

let distance = 30;

let duration = 0.4;

let cooldown = 0.4;

export {
  shaderName,
  outline2pxSource,
  load,
  distance,
  duration,
  cooldown,
  cast,
  move,
}
/* outline2pxSource Not a pure module */
