// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Z$Kaplay from "@nojaf/rescript-kaplay/src/Components/Z.res.mjs";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.mjs";
import * as Pos$Kaplay from "@nojaf/rescript-kaplay/src/Components/Pos.res.mjs";
import * as Math$Kaplay from "@nojaf/rescript-kaplay/src/Math.res.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.mjs";
import * as Anchor$Kaplay from "@nojaf/rescript-kaplay/src/Components/Anchor.res.mjs";
import * as Shader$Kaplay from "@nojaf/rescript-kaplay/src/Components/Shader.res.mjs";
import * as Team$Skirmish from "../Team.res.mjs";
import * as Wall$Skirmish from "../Wall.res.mjs";
import * as Attack$Skirmish from "./Attack.res.mjs";
import * as GameObjRaw$Kaplay from "@nojaf/rescript-kaplay/src/Components/GameObjRaw.res.mjs";
import * as GameContext$Skirmish from "../GameContext.res.mjs";
import GlowFragraw from "../../shaders/glow.frag?raw";
import DarkenFragraw from "../../shaders/darken.frag?raw";
import Outline2pxFragraw from "../../shaders/outline2px.frag?raw";

Pos$Kaplay.Comp({});

Anchor$Kaplay.Comp({});

GameObjRaw$Kaplay.Comp({});

Z$Kaplay.Comp({});

Shader$Kaplay.Comp({});

let include = Attack$Skirmish.Comp({});

let addAttackWithTag = include.addAttackWithTag;

let glowSource = GlowFragraw;

let outline2pxSource = Outline2pxFragraw;

let darkenSource = DarkenFragraw;

function load() {
  GameContext$Skirmish.k.loadShader("glow", undefined, glowSource);
  GameContext$Skirmish.k.loadShader("outline2px", undefined, outline2pxSource);
  GameContext$Skirmish.k.loadShader("darken", undefined, darkenSource);
}

let lighting = GameContext$Skirmish.k.Color.fromHex("#fef9c2");

function draw() {
  let t = this ;
  let localPoints = t.points.map(point => t.fromWorld(point));
  GameContext$Skirmish.k.drawLines({
    pts: localPoints,
    color: lighting,
    width: 2,
    cap: "square"
  });
}

function drawInspect() {
  let t = this ;
  let rectInLocal = t.fromWorld(t.worldRect.pos);
  GameContext$Skirmish.k.drawRect({
    pos: rectInLocal,
    outline: {
      width: 2,
      color: GameContext$Skirmish.k.BLUE
    },
    width: t.worldRect.width,
    height: t.worldRect.height,
    fill: false
  });
}

let up = GameContext$Skirmish.k.Vec2.UP.scale(40);

let down = GameContext$Skirmish.k.Vec2.DOWN.scale(40);

function expandRectWithPoint(currentRect, newPoint) {
  let currentMinX = currentRect.pos.x;
  let currentMaxX = currentRect.pos.x + currentRect.width;
  let currentMinY = currentRect.pos.y;
  let currentMaxY = currentRect.pos.y + currentRect.height;
  let newMinX = Math.min(currentMinX, newPoint.x);
  let newMaxX = Math.max(currentMaxX, newPoint.x);
  let newMinY = Math.min(currentMinY, newPoint.y);
  let newMaxY = Math.max(currentMaxY, newPoint.y);
  let newWidth = newMaxX - newMinX;
  let newHeight = newMaxY - newMinY;
  return Math$Kaplay.Rect.makeWorld(GameContext$Skirmish.k, GameContext$Skirmish.k.vec2(newMinX, newMinY), newWidth, newHeight);
}

function destroy(pokemon, thundershock) {
  thundershock.timerRef.cancel();
  GameContext$Skirmish.k.wait(5 * 0.050, () => {
    pokemon.unuse(Shader$Kaplay.id);
    pokemon.mobility = true;
    thundershock.destroy();
  });
}

function cast(pokemon) {
  pokemon.mobility = false;
  let direction = pokemon.facing === true ? up : down;
  let otherPokemon = GameContext$Skirmish.k.query({
    include: ["pokemon"]
  }).filter(p => p.id !== pokemon.id);
  let thundershock = pokemon.add(Belt_Array.concatMany([
    [
      GameContext$Skirmish.k.pos(0, 0),
      GameContext$Skirmish.k.z(-1),
      Team$Skirmish.getTagComponent(pokemon.team),
      {
        id: "thundershock",
        draw: draw,
        drawInspect: drawInspect
      }
    ],
    addAttackWithTag(function () {
      let thundershock = this ;
      return thundershock.worldRect;
    })
  ]));
  thundershock.use({
    points: [pokemon.worldPos()],
    timerRef: GameContext$Skirmish.k.loop(0.050, extra => {
      let pkmnWorldPos = pokemon.worldPos();
      let point = Stdlib_Array.last(thundershock.points);
      let lastPoint = point !== undefined ? point : pkmnWorldPos;
      let deviationX = GameContext$Skirmish.k.rand(-1 * 7, 7);
      let candidate = GameContext$Skirmish.k.vec2(pkmnWorldPos.x + deviationX, lastPoint.y + direction.y);
      let validCandidate = Wall$Skirmish.worldRect.contains(candidate);
      let safeCandidate = validCandidate ? candidate : GameContext$Skirmish.k.vec2(GameContext$Skirmish.k.clamp(candidate.x, 0, GameContext$Skirmish.k.width()), GameContext$Skirmish.k.clamp(candidate.y, 0, GameContext$Skirmish.k.height()));
      thundershock.points.push(safeCandidate);
      thundershock.worldRect = expandRectWithPoint(thundershock.worldRect, safeCandidate);
      if (!validCandidate) {
        destroy(pokemon, thundershock);
      }
      otherPokemon.forEach(otherPokemon => {
        if (thundershock.points.some(point => otherPokemon.hasPoint(point))) {
          otherPokemon.hp = otherPokemon.hp - 5 | 0;
          return destroy(pokemon, thundershock);
        }
      });
    }),
    worldRect: Math$Kaplay.Rect.makeWorld(GameContext$Skirmish.k, pokemon.worldPos(), 0, 0)
  });
  pokemon.use(GameContext$Skirmish.k.shader("glow", () => ({
    u_time: GameContext$Skirmish.k.time(),
    u_resolution: GameContext$Skirmish.k.vec2(pokemon.width, pokemon.height),
    u_thickness: 0.7,
    u_color: lighting,
    u_intensity: 0.66,
    u_pulse_speed: 5.0
  })));
}

function move_cast(_k, pkmn) {
  cast(pkmn);
}

function move_addRulesForAI(_k, _rs, _slot, _facts) {
  
}

let move = {
  id: 2,
  name: "Thundershock",
  maxPP: 30,
  baseDamage: 40,
  coolDownDuration: 1,
  cast: move_cast,
  addRulesForAI: move_addRulesForAI
};

export {
  load,
  cast,
  move,
}
/*  Not a pure module */
