// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Z$Kaplay from "@nojaf/rescript-kaplay/src/Components/Z.res.mjs";
import * as Pos$Kaplay from "@nojaf/rescript-kaplay/src/Components/Pos.res.mjs";
import * as Math$Kaplay from "@nojaf/rescript-kaplay/src/Math.res.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Anchor$Kaplay from "@nojaf/rescript-kaplay/src/Components/Anchor.res.mjs";
import * as Shader$Kaplay from "@nojaf/rescript-kaplay/src/Components/Shader.res.mjs";
import * as GameObjRaw$Kaplay from "@nojaf/rescript-kaplay/src/Components/GameObjRaw.res.mjs";
import * as GameContext$Skirmish from "../GameContext.res.mjs";
import GlowFragraw from "../../shaders/glow.frag?raw";
import DarkenFragraw from "../../shaders/darken.frag?raw";
import Outline2pxFragraw from "../../shaders/outline2px.frag?raw";

Pos$Kaplay.Comp({});

Anchor$Kaplay.Comp({});

GameObjRaw$Kaplay.Comp({});

Z$Kaplay.Comp({});

Shader$Kaplay.Comp({});

let glowSource = GlowFragraw;

let outline2pxSource = Outline2pxFragraw;

let darkenSource = DarkenFragraw;

function load() {
  GameContext$Skirmish.k.loadShader("glow", undefined, glowSource);
  GameContext$Skirmish.k.loadShader("outline2px", undefined, outline2pxSource);
  GameContext$Skirmish.k.loadShader("darken", undefined, darkenSource);
}

let lighting = GameContext$Skirmish.k.Color.fromHex("#fef9c2");

function draw() {
  let t = this ;
  let localPoints = t.points.map(point => t.fromWorld(point));
  GameContext$Skirmish.k.drawLines({
    pts: localPoints,
    color: lighting,
    width: 2,
    cap: "square"
  });
}

let worldRect = Math$Kaplay.Rect.makeWorld(GameContext$Skirmish.k, GameContext$Skirmish.k.Vec2.ZERO, GameContext$Skirmish.k.width(), GameContext$Skirmish.k.height());

let up = GameContext$Skirmish.k.Vec2.UP.scale(20);

let down = GameContext$Skirmish.k.Vec2.DOWN.scale(20);

function destroy(pokemon, thundershock) {
  thundershock.timerRef.cancel();
  GameContext$Skirmish.k.wait(5 * 0.050, () => {
    pokemon.unuse("shader");
    pokemon.mobility = true;
    pokemon.attackStatus = true;
    thundershock.destroy();
  });
}

function cast(pokemon) {
  pokemon.mobility = false;
  pokemon.attackStatus = false;
  let direction = pokemon.facing === true ? up : down;
  let otherPokemon = GameContext$Skirmish.k.query({
    include: ["pokemon"]
  }).filter(p => p.id !== pokemon.id);
  let thundershock = pokemon.add([
    GameContext$Skirmish.k.pos(0, 0),
    GameContext$Skirmish.k.z(-1),
    {
      id: "thundershock",
      draw: draw
    }
  ]);
  thundershock.use({
    points: [pokemon.worldPos()],
    timerRef: GameContext$Skirmish.k.loop(0.050, extra => {
      let pkmnWorldPos = pokemon.worldPos();
      let point = Stdlib_Array.last(thundershock.points);
      let lastPoint = point !== undefined ? point : pkmnWorldPos;
      let deviationX = GameContext$Skirmish.k.rand(-1 * 7, 7);
      let candidate = GameContext$Skirmish.k.vec2(pkmnWorldPos.x + deviationX, lastPoint.y + direction.y);
      if (worldRect.contains(candidate)) {
        thundershock.points.push(candidate);
      } else {
        let cap = GameContext$Skirmish.k.vec2(GameContext$Skirmish.k.clamp(candidate.x, 0, GameContext$Skirmish.k.width()), GameContext$Skirmish.k.clamp(candidate.y, 0, GameContext$Skirmish.k.height()));
        thundershock.points.push(cap);
        destroy(pokemon, thundershock);
      }
      otherPokemon.forEach(otherPokemon => {
        if (thundershock.points.some(point => otherPokemon.hasPoint(point))) {
          otherPokemon.hp = otherPokemon.hp - 1 | 0;
          return destroy(pokemon, thundershock);
        }
      });
    })
  });
  pokemon.use(GameContext$Skirmish.k.shader("glow", () => ({
    u_time: GameContext$Skirmish.k.time(),
    u_resolution: GameContext$Skirmish.k.vec2(pokemon.width, pokemon.height),
    u_thickness: 0.7,
    u_color: lighting,
    u_intensity: 0.66,
    u_pulse_speed: 5.0
  })));
}

export {
  load,
  cast,
}
/*  Not a pure module */
