// Generated by ReScript, PLEASE EDIT WITH CARE


function move_cast(param, param$1) {
  
}

function move_addRulesForAI(param, param$1, param$2, param$3) {
  
}

let move = {
  id: -1,
  name: "Zero move",
  maxPP: 0,
  baseDamage: 0,
  coolDownDuration: 0,
  cast: move_cast,
  addRulesForAI: move_addRulesForAI
};

export {
  move,
}
/* No side effect */
