// Generated by ReScript, PLEASE EDIT WITH CARE


function move_cast(param, param$1) {
  
}

function move_addRulesForAI(param, param$1, param$2, param$3) {
  
}

let move = {
  id: -1,
  name: "Zero move",
  maxPP: 0,
  baseDamage: 0,
  coolDownDuration: 0,
  cast: move_cast,
  addRulesForAI: move_addRulesForAI
};

let moveSlot = {
  move: move,
  currentPP: 0,
  lastUsedAt: - Infinity
};

export {
  move,
  moveSlot,
}
/* moveSlot Not a pure module */
