// Generated by ReScript, PLEASE EDIT WITH CARE


let mathRect = (function (k, pos, width, height) {
    return new k.Rect(pos, width, height);
});

let mathCircle = (function (k, center, radius) {
    return new k.Circle(center, radius);
});

let mathPolygon = (function (k,  points) {
    return new k.Polygon(points);
});

let Level = {};

export {
  mathRect,
  mathCircle,
  mathPolygon,
  Level,
}
/* No side effect */
