// Generated by ReScript, PLEASE EDIT WITH CARE


let colorFromRGB = (function (k, r, g, b) {
    return new k.Color(r,g,b);
});

let Level = {};

export {
  colorFromRGB,
  Level,
}
/* No side effect */
