// Generated by ReScript, PLEASE EDIT WITH CARE


let makeLocal = (function (k, pos, width, height) {
    return new k.Rect(pos, width, height);
});

let makeWorld = (function (k, pos, width, height) {
    return new k.Rect(pos, width, height);
});

let Rect = {
  makeLocal: makeLocal,
  makeWorld: makeWorld
};

let makeLocal$1 = (function (k, center, radius) {
    return new k.Circle(center, radius);
});

let makeWorld$1 = (function (k, center, radius) {
    return new k.Circle(center, radius);
});

let Circle = {
  makeLocal: makeLocal$1,
  makeWorld: makeWorld$1
};

let makeLocal$2 = (function (k,  points) {
    return new k.Polygon(points);
});

let makeWorld$2 = (function (k,  points) {
    return new k.Polygon(points);
});

let Polygon = {
  makeLocal: makeLocal$2,
  makeWorld: makeWorld$2
};

export {
  Rect,
  Circle,
  Polygon,
}
/* No side effect */
