// Generated by ReScript, PLEASE EDIT WITH CARE


let make = (function (k, pos, width, height) {
    return new k.Rect(pos, width, height);
});

let Rect = {
  make: make
};

let make$1 = (function (k, center, radius) {
    return new k.Circle(center, radius);
});

let Circle = {
  make: make$1
};

let make$2 = (function (k,  points) {
    return new k.Polygon(points);
});

let Polygon = {
  make: make$2
};

export {
  Rect,
  Circle,
  Polygon,
}
/* No side effect */
