// Generated by ReScript, PLEASE EDIT WITH CARE


let empty = ({
    timeLeft: 0,
    currentTime: 0,
    paused: false,
    cancel: function() {},
    onEnd: function() {},
    then: function(action) { return this; },
    finish: function() {},
});

export {
  empty,
}
/* empty Not a pure module */
