// Generated by ReScript, PLEASE EDIT WITH CARE


function Impl(T) {
  return {};
}

let World = {};

let Screen = {};

let Local = {};

let Tile = {};

let Unit = {};

export {
  Impl,
  World,
  Screen,
  Local,
  Tile,
  Unit,
}
/* No side effect */
