// Generated by ReScript, PLEASE EDIT WITH CARE

import Kaplay from "kaplay";
import * as Vitest from "vitest";
import * as Ember$Skirmish from "../src/Moves/Ember.res.mjs";
import * as EnemyAI$Skirmish from "../src/EnemyAI.res.mjs";
import * as Pokemon$Skirmish from "../src/Pokemon.res.mjs";

Vitest.test("create kaplay context", () => {
  let k = Kaplay({
    width: 300,
    height: 400,
    global: false,
    background: "#000000",
    scale: 1,
    crisp: true
  });
  Vitest.expect(k).toBeDefined();
  Pokemon$Skirmish.load(k, 4);
  Pokemon$Skirmish.load(k, 1);
  Ember$Skirmish.load();
  return new Promise((resolve, reject) => {
    k.onError(error => reject(error));
    k.onLoad(() => {
      let charmander = Pokemon$Skirmish.make(k, 4, 5, false);
      let bulbasaur = Pokemon$Skirmish.make(k, 1, 5, true);
      Vitest.expect(charmander).toBeDefined();
      EnemyAI$Skirmish.make(k, 4, 5, bulbasaur);
      k.quit();
      resolve();
    });
  });
});

/*  Not a pure module */
