// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Pos$Kaplay from "@nojaf/rescript-kaplay/src/Components/Pos.res.mjs";
import * as Math$Kaplay from "@nojaf/rescript-kaplay/src/Math.res.mjs";
import * as Rect$Kaplay from "@nojaf/rescript-kaplay/src/Components/Rect.res.mjs";
import * as Color$Kaplay from "@nojaf/rescript-kaplay/src/Components/Color.res.mjs";
import * as Anchor$Kaplay from "@nojaf/rescript-kaplay/src/Components/Anchor.res.mjs";
import * as Team$Skirmish from "../src/Team.res.mjs";
import * as Attack$Skirmish from "../src/Moves/Attack.res.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as GameObjRaw$Kaplay from "@nojaf/rescript-kaplay/src/Components/GameObjRaw.res.mjs";

GameObjRaw$Kaplay.Comp({});

Pos$Kaplay.Comp({});

Rect$Kaplay.Comp({});

let include = Attack$Skirmish.Comp({});

let getClosestCorner = include.getClosestCorner;

let addAttack = include.addAttack;

Anchor$Kaplay.Comp({});

Color$Kaplay.Comp({});

function getCorner(attack, k) {
  let pkmn = k.query({
      include: [Team$Skirmish.opponent]
    })[0];
  if (pkmn === undefined) {
    return;
  }
  let pkmnPos = Primitive_option.valFromOption(pkmn).worldPos();
  let closestCorner = getClosestCorner(attack, k, pkmnPos);
  return attack.fromWorld(closestCorner);
}

function make(k, x, y, size, team) {
  let gameObj = k.add(Belt_Array.concatMany([
    [
      k.pos(x, y),
      k.anchor("center"),
      Team$Skirmish.getTagComponent(team)
    ],
    addAttack(function () {
      let gameObj = this ;
      let halfSize = size / 2;
      let worldPos = gameObj.worldPos();
      return Math$Kaplay.Rect.makeWorld(k, k.vec2(worldPos.x - halfSize, worldPos.y - halfSize), size, size);
    }),
    [{
        id: "generic-move",
        draw: function () {
          let gameObj = this ;
          let color = team === true ? k.Color.fromHex("#00bcff") : k.Color.fromHex("#ff2056");
          k.drawRect({
            pos: k.vec2(- size / 2, - size / 2),
            color: color,
            width: size,
            height: size
          });
          let corner = getCorner(gameObj, k);
          if (corner !== undefined) {
            k.drawCircle({
              pos: corner,
              color: k.YELLOW,
              radius: 3
            });
            return;
          }
        }
      }]
  ]));
  k.onClick(() => {
    let mousePos = k.mousePos();
    let worldPos = k.toWorld(mousePos);
    gameObj.worldPos(worldPos);
  });
  return gameObj;
}

export {
  getClosestCorner,
  addAttack,
  getCorner,
  make,
}
/*  Not a pure module */
