// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pos$Kaplay from "@nojaf/rescript-kaplay/src/Components/Pos.res.mjs";

Pos$Kaplay.Comp({});

function make(k, rs) {
  k.add([
    k.pos(15, k.height() - 15),
    {
      id: "debug-rule-system",
      draw: function () {
        rs.facts.entries().toArray().forEach((param, index) => {
          let posY = -20 * index;
          let gradeText = (param[1] * 100).toFixed(2);
          let text = param[0] + `: ` + gradeText + `%`;
          k.drawText({
            pos: k.vec2(0, posY),
            color: k.WHITE,
            text: text,
            size: 15
          });
        });
      }
    }
  ]);
}

export {
  make,
}
/*  Not a pure module */
