// Generated by ReScript, PLEASE EDIT WITH CARE

import Sharp from "sharp";
import * as Process from "process";
import * as Nodepath from "node:path";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.mjs";

function decodePokemonSprite(json) {
  if (typeof json !== "object" || json === null || Array.isArray(json)) {
    return;
  }
  let match = json.sprites;
  if (typeof match !== "object" || match === null || Array.isArray(match)) {
    return;
  }
  let back = match.back_default;
  if (typeof back !== "string") {
    return;
  }
  let front = match.front_default;
  if (typeof front === "string") {
    return {
      front: front,
      back: back
    };
  }
}

function isNumeric(str) {
  let parsed = parseFloat(str);
  return !Number.isNaN(parsed);
}

async function downloadSprite(spriteUrl, fileName) {
  let imageResponse = await fetch(spriteUrl);
  if (imageResponse.ok) {
    let blob = await imageResponse.blob();
    let arrayBuffer = await blob.arrayBuffer();
    let buffer = Buffer.from(arrayBuffer);
    let sharpInstance = Sharp(buffer);
    let trimmed = sharpInstance.trim();
    let resized = trimmed.resize({
      width: 32,
      height: 32,
      fit: "contain",
      background: {
        r: 0,
        g: 0,
        b: 0,
        alpha: 0
      }
    }).png();
    let outputPath = Nodepath.join(__dirname, "..", "public", "sprites", fileName);
    await resized.toFile(outputPath);
    console.log(`Created sprite for ` + fileName);
    return;
  }
  let status = imageResponse.status;
  let statusText = imageResponse.statusText;
  console.error(`Failed to fetch sprite image`);
  console.error(`URL: ` + spriteUrl);
  console.error(`Status: ` + status.toString() + ` ` + statusText);
  Process.exit(1);
}

async function main(identifier) {
  let trimmedIdentifier = identifier.trim();
  let url = `https://pokeapi.co/api/v2/pokemon/` + trimmedIdentifier + `/`;
  try {
    let response = await fetch(url);
    if (response.ok) {
      let json = await response.json();
      let match = decodePokemonSprite(json);
      if (match !== undefined) {
        try {
          await downloadSprite(match.front, trimmedIdentifier + `-front.png`);
          await downloadSprite(match.back, trimmedIdentifier + `-back.png`);
          console.log(`Created sprites for ` + trimmedIdentifier);
          return;
        } catch (raw_exn) {
          let exn = Primitive_exceptions.internalToException(raw_exn);
          console.error(`Error during image processing`);
          console.error(exn);
          Process.exit(1);
          return;
        }
      } else {
        let helpText = isNumeric(trimmedIdentifier) ? "Could not find Pokemon with that ID" : "Could not find Pokemon with that name";
        console.error(`Error: ` + helpText);
        console.error(`URL: ` + url);
        Process.exit(1);
        return;
      }
    } else {
      let status = response.status;
      let statusText = response.statusText;
      let responseBody;
      try {
        responseBody = await response.text();
      } catch (exn$1) {
        responseBody = undefined;
      }
      console.error(`Fetch failed for URL: ` + url);
      console.error(`Status: ` + status.toString() + ` ` + statusText);
      if (responseBody !== undefined) {
        console.error(`Response body: ` + responseBody);
      }
      let helpText$1 = isNumeric(trimmedIdentifier) ? `Invalid Pokemon ID: ` + trimmedIdentifier : `Invalid Pokemon name: ` + trimmedIdentifier;
      console.error(helpText$1);
      Process.exit(1);
      return;
    }
  } catch (raw_exn$1) {
    let exn$2 = Primitive_exceptions.internalToException(raw_exn$1);
    console.error(`Error fetching Pokemon data`);
    console.error(`URL: ` + url);
    console.error(exn$2);
    let helpText$2 = isNumeric(trimmedIdentifier) ? `Invalid Pokemon ID: ` + trimmedIdentifier : `Invalid Pokemon name: ` + trimmedIdentifier;
    console.error(helpText$2);
    Process.exit(1);
    return;
  }
}

function parseArgs() {
  let args = Bun.argv;
  let scriptArgs = args.slice(2);
  let identifier = scriptArgs[0];
  if (identifier !== undefined) {
    return identifier;
  } else {
    console.error("Error: Required parameter is missing. Provide a Pokemon name or ID.");
    Process.exit(1);
    return;
  }
}

let required = parseArgs();

if (required !== undefined) {
  await main(required);
}

export {
  decodePokemonSprite,
  isNumeric,
  downloadSprite,
  main,
  parseArgs,
}
/* required Not a pure module */
