// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pokemon$Skirmish from "./Pokemon.res.mjs";
import * as RuleSystem$Kaplay from "@nojaf/rescript-kaplay/src/RuleSystem.res.mjs";

let playerCentered = "playerCentered";

let playerBelow = "playerBelow";

let Facts = {
  playerCentered: playerCentered,
  playerBelow: playerBelow
};

function isPlayerCentered(rs) {
  let distance = Math.round(Math.abs(rs.state.self.pos.x - rs.state.opponent.pos.x));
  return distance === 0;
}

function isPlayerBelow(rs) {
  return rs.state.self.pos.y < rs.state.opponent.pos.y;
}

function negate(predicate) {
  return rs => !predicate(rs);
}

function make(k, pokemonId, level, player) {
  let enemy = Pokemon$Skirmish.make(k, pokemonId, level, false);
  let rs = RuleSystem$Kaplay.make(k);
  rs.state = {
    self: enemy,
    opponent: player,
    lastAttackAt: 0
  };
  rs.addRuleAssertingFact(isPlayerCentered, playerCentered, 1);
  rs.addRuleRetractingFact(rs => !isPlayerCentered(rs), playerCentered, 1);
  rs.addRuleAssertingFact(isPlayerBelow, playerBelow, 1);
  rs.addRuleRetractingFact(rs => !isPlayerBelow(rs), playerBelow, 1);
  enemy.onUpdate(() => {
    rs.reset();
    rs.execute();
    let g = rs.gradeForFact(playerCentered);
    if (g >= 1.0) {
      return;
    }
    let deltaX = Math.round(player.pos.x - enemy.pos.x);
    if (deltaX === 0) {
      return;
    }
    let x = deltaX > 0 ? 120 : -120;
    enemy.move(k.vec2(x, 0));
  });
  k.onKeyPress(key => {
    if (key !== "f1" && key !== "shift" && key !== "f2" && key !== "down" && key !== "f3" && key !== "up" && key !== "f4" && key !== "right" && key !== "f5" && key !== "left" && key !== "f6" && key !== " " && key !== "f7" && key !== "space" && key !== "f8" && key !== "meta" && key !== "f9" && key !== "alt" && key !== "f10" && key !== "control" && key !== "f11" && key !== "tab" && key !== "f12" && key !== "enter" && key !== "`" && key !== "backspace" && key !== "1" && key !== "escape" && key !== "2" && key !== "/" && key !== "3" && key !== "." && key !== "4" && key !== "," && key !== "5" && key !== "m" && key !== "6" && key !== "n" && key !== "7" && key !== "b" && key !== "8" && key !== "v" && key !== "9" && key !== "c" && key !== "0" && key !== "x" && key !== "-" && key !== "z" && key !== "+" && key !== "'" && key !== "=" && key !== ";" && key !== "q" && key !== "l" && key !== "w" && key !== "k" && key !== "e" && key !== "j" && key !== "r" && key !== "h" && key !== "t" && key !== "g" && key !== "y" && key !== "f" && key !== "u" && key !== "d" && key !== "i" && key !== "s" && key !== "o" && key !== "a" && key !== "p" && key !== "\\" && key !== "[" && key !== "]") {
      return;
    }
    if (key !== "space") {
      return;
    }
    console.table(rs.facts.entries().toArray());
  });
  return enemy;
}

export {
  Facts,
  isPlayerCentered,
  isPlayerBelow,
  negate,
  make,
}
/* Pokemon-Skirmish Not a pure module */
