// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pokemon$Skirmish from "./Pokemon.res.mjs";

function addEnemyAI(player) {
  let update = function () {
    let self = this ;
    self.move(self.direction.scale(20));
  };
  return {
    id: "enemy-ai",
    update: update
  };
}

function make(pokemonId, level, player) {
  let gameObj = Pokemon$Skirmish.make(pokemonId, level, "Opponent");
  gameObj.use(addEnemyAI(player));
  return gameObj;
}

export {
  addEnemyAI,
  make,
}
/* Pokemon-Skirmish Not a pure module */
