// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.mjs";
import * as Team$Skirmish from "./Team.res.mjs";
import * as Attack$Skirmish from "./Moves/Attack.res.mjs";
import * as AIFacts$Skirmish from "./EnemyAI/AIFacts.res.mjs";
import * as Pokemon$Skirmish from "./Pokemon.res.mjs";
import * as RuleSystem$Kaplay from "@nojaf/rescript-kaplay/src/RuleSystem.res.mjs";
import * as BaseFacts$Skirmish from "./EnemyAI/BaseFacts.res.mjs";
import * as MoveFacts$Skirmish from "./EnemyAI/MoveFacts.res.mjs";
import * as DerivedFacts$Skirmish from "./EnemyAI/DerivedFacts.res.mjs";
import * as DefensiveFacts$Skirmish from "./EnemyAI/DefensiveFacts.res.mjs";
import * as DebugRuleSystem$Skirmish from "./DebugRuleSystem.res.mjs";

let AttackFacts = {
  shouldAttack: AIFacts$Skirmish.shouldAttack
};

function makeRuleSystem(k, enemy, player) {
  let rs = RuleSystem$Kaplay.make(k);
  rs.state = {
    enemy: enemy,
    player: player,
    playerAttacks: [],
    horizontalMovement: undefined,
    lastAttackAt: 0
  };
  BaseFacts$Skirmish.addRules(k, rs);
  DerivedFacts$Skirmish.addRules(rs);
  DefensiveFacts$Skirmish.addRules(rs);
  MoveFacts$Skirmish.addRules(k, rs);
  return rs;
}

function getPlayerAttacks(k) {
  return Stdlib_Array.filterMap(k.query({
    include: [
      Attack$Skirmish.tag,
      Team$Skirmish.player
    ],
    hierarchy: "descendants"
  }), Attack$Skirmish.Unit.fromGameObj);
}

function update(k, rs, param) {
  rs.reset();
  rs.state.playerAttacks = getPlayerAttacks(k);
  rs.execute();
  let match = rs.state.horizontalMovement;
  if (match !== undefined) {
    if (match === true) {
      Pokemon$Skirmish.moveLeft(k, rs.state.enemy);
    } else {
      Pokemon$Skirmish.moveRight(k, rs.state.enemy);
    }
  }
  let g = rs.gradeForFact(AIFacts$Skirmish.shouldAttack);
  if (g <= 0.0) {
    return;
  }
  let moveIndex = MoveFacts$Skirmish.selectMove(rs);
  if (moveIndex !== undefined) {
    return Pokemon$Skirmish.tryCastMove(k, rs.state.enemy, moveIndex);
  }
}

function make(k, enemy, player) {
  let rs = makeRuleSystem(k, enemy, player);
  enemy.onUpdate(extra => update(k, rs, extra));
  if (k.debug.inspect) {
    return DebugRuleSystem$Skirmish.make(k, rs);
  }
}

let BaseFacts = {
  addRules: BaseFacts$Skirmish.addRules
};

let DerivedFacts = {
  addRules: DerivedFacts$Skirmish.addRules
};

let DefensiveFacts = {
  addRules: DefensiveFacts$Skirmish.addRules
};

let MoveFacts = {
  selectMove: MoveFacts$Skirmish.selectMove
};

export {
  BaseFacts,
  DerivedFacts,
  DefensiveFacts,
  AttackFacts,
  MoveFacts,
  make,
  makeRuleSystem,
  update,
}
/* Attack-Skirmish Not a pure module */
