// Generated by ReScript, PLEASE EDIT WITH CARE

import Kaplay from "kaplay";
import * as Primitive_float from "@rescript/runtime/lib/es6/Primitive_float.js";

let scale = Primitive_float.min(1.5, Primitive_float.min(window.innerWidth / 360, window.innerHeight / 649));

let k = Kaplay({
  width: 360,
  height: 649,
  global: false,
  background: "#e5e7eb",
  scale: scale,
  crisp: true
});

k.debug.inspect = true;

let gameWidth = 360;

let gameHeight = 649;

export {
  gameWidth,
  gameHeight,
  scale,
  k,
}
/* scale Not a pure module */
