// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pos$Kaplay from "@nojaf/rescript-kaplay/src/Components/Pos.res.mjs";
import * as Area$Kaplay from "@nojaf/rescript-kaplay/src/Components/Area.res.mjs";
import * as Math$Kaplay from "@nojaf/rescript-kaplay/src/Math.res.mjs";
import * as Text$Kaplay from "@nojaf/rescript-kaplay/src/Components/Text.res.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as GameObjRaw$Kaplay from "@nojaf/rescript-kaplay/src/Components/GameObjRaw.res.mjs";
import * as PkmnFont$Skirmish from "./PkmnFont.res.mjs";
import * as GameContext$Skirmish from "./GameContext.res.mjs";

GameObjRaw$Kaplay.Comp({});

Pos$Kaplay.Comp({});

Area$Kaplay.Comp({});

Text$Kaplay.Comp({});

function make(k) {
  let rect = Math$Kaplay.Rect.makeLocal(k, k.Vec2.ZERO, 180, 50);
  let btn = k.add([
    k.pos(k.vec2(k.width() / 2 - rect.width / 2, k.height() * 0.66)),
    k.area({
      shape: Primitive_option.some(rect)
    }),
    {
      id: "button",
      draw: function () {
        k.drawRect({
          pos: k.vec2(0, 0),
          color: k.Color.fromHex("#fb2c36"),
          outline: {
            width: 4,
            color: k.Color.fromHex("#c10007")
          },
          width: rect.width,
          height: rect.height
        });
        k.drawText({
          pos: k.vec2(20, 15),
          text: "Play Again",
          font: Primitive_option.some(PkmnFont$Skirmish.font),
          size: 20
        });
      }
    }
  ]);
  btn.onClick(() => {
    k.go("game");
  });
  let defaultCursor = k.getCursor();
  btn.onHover(() => {
    k.setCursor("pointer");
  });
  btn.onHoverEnd(() => {
    k.setCursor(defaultCursor);
  });
}

let Button = {
  make: make
};

function scene(teamWhoLost) {
  PkmnFont$Skirmish.load(GameContext$Skirmish.k);
  GameContext$Skirmish.k.onLoad(() => {
    GameContext$Skirmish.k.add([{
        id: "victory-screen",
        draw: function () {
          GameContext$Skirmish.k.drawText({
            pos: GameContext$Skirmish.k.vec2(0, GameContext$Skirmish.k.height() / 4),
            color: GameContext$Skirmish.k.BLACK,
            text: teamWhoLost === false ? "You win!" : "You lose!",
            font: Primitive_option.some(PkmnFont$Skirmish.font),
            size: 32,
            align: "center",
            width: GameContext$Skirmish.k.width()
          });
        }
      }]);
    make(GameContext$Skirmish.k);
  });
}

let sceneName = "victory-screen";

export {
  Button,
  sceneName,
  scene,
}
/*  Not a pure module */
