// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pokemon$Skirmish from "./Pokemon.res.mjs";
import * as GameContext$Skirmish from "./GameContext.res.mjs";
import * as Thundershock$Skirmish from "./Thundershock.res.mjs";

function sceneLoaded() {
  Pokemon$Skirmish.make(25);
}

function scene() {
  Pokemon$Skirmish.load(25);
  Thundershock$Skirmish.load();
  GameContext$Skirmish.k.onLoad(sceneLoaded);
}

export {
  sceneLoaded,
  scene,
}
/* Pokemon-Skirmish Not a pure module */
