// Generated by ReScript, PLEASE EDIT WITH CARE

import Kaplay from "kaplay";
import * as Primitive_float from "@rescript/runtime/lib/es6/Primitive_float.js";

let scale = Primitive_float.min(1.5, Primitive_float.min(window.innerWidth / 800, window.innerHeight / 400));

let k = Kaplay({
  width: 300,
  height: 400,
  global: false,
  background: "#e5e7eb",
  scale: scale,
  crisp: true
});

export {
  scale,
  k,
}
/* scale Not a pure module */
