// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pos$Kaplay from "@nojaf/rescript-kaplay/src/Components/Pos.res.mjs";
import * as Pokemon$Skirmish from "./Pokemon.res.mjs";
import * as GameContext$Skirmish from "./GameContext.res.mjs";

Pos$Kaplay.Comp({});

let good = GameContext$Skirmish.k.Color.fromHex("#00bc7d");

let middle = GameContext$Skirmish.k.Color.fromHex("#ffdf20");

let bad = GameContext$Skirmish.k.Color.fromHex("#e7000b");

function getHealthColor(healthPercent) {
  if (healthPercent >= 70) {
    let t = (100 - healthPercent) / 30;
    return good.lerp(middle, t);
  }
  if (healthPercent < 40) {
    return bad;
  }
  let t$1 = (70 - healthPercent) / 30;
  return middle.lerp(bad, t$1);
}

function setHealth(healthbar, targetPercent) {
  let controller = healthbar.tweenControllerRef;
  if (controller !== undefined) {
    controller.cancel();
  }
  let controller$1 = GameContext$Skirmish.k.tween(healthbar.healthPercentage, targetPercent, 0.33, value => {
    healthbar.healthPercentage = value;
  }, GameContext$Skirmish.k.easings.easeOutSine);
  controller$1.onEnd(() => {
    healthbar.tweenControllerRef = undefined;
  });
  healthbar.tweenControllerRef = controller$1;
}

function draw() {
  let healthbar = this ;
  GameContext$Skirmish.k.drawLines({
    pts: [
      GameContext$Skirmish.k.Vec2.ZERO,
      GameContext$Skirmish.k.vec2(0, 40),
      GameContext$Skirmish.k.vec2(GameContext$Skirmish.k.width() / 2, 40)
    ],
    color: GameContext$Skirmish.k.BLACK,
    width: 2
  });
  GameContext$Skirmish.k.drawText({
    pos: GameContext$Skirmish.k.vec2(5, 0),
    color: GameContext$Skirmish.k.BLACK,
    text: "Charmander".toUpperCase(),
    font: "system-ui",
    size: 15,
    letterSpacing: 0.5
  });
  GameContext$Skirmish.k.drawText({
    pos: GameContext$Skirmish.k.vec2(5, 26),
    color: GameContext$Skirmish.k.BLACK,
    text: "HP:",
    size: 7
  });
  GameContext$Skirmish.k.drawRect({
    pos: GameContext$Skirmish.k.vec2(20, 26),
    color: GameContext$Skirmish.k.Color.fromHex("#e5e7eb"),
    outline: {
      width: 1,
      color: GameContext$Skirmish.k.BLACK
    },
    width: 100,
    height: 6,
    radius: [
      3,
      3,
      3,
      3
    ]
  });
  let animatedPercent = healthbar.healthPercentage;
  let healthColor = getHealthColor(animatedPercent);
  let healthbarWidth = healthbar.healthPercentage;
  GameContext$Skirmish.k.drawRect({
    pos: GameContext$Skirmish.k.vec2(20, 26),
    color: healthColor,
    width: healthbarWidth,
    height: 5,
    radius: [
      3,
      0,
      0,
      3
    ]
  });
}

function make(pokemon) {
  let healthbar = GameContext$Skirmish.k.add([
    {
      healthPercentage: Pokemon$Skirmish.getHealthPercentage(pokemon)
    },
    {
      id: "healthbar",
      draw: draw
    },
    GameContext$Skirmish.k.pos(10, 10)
  ]);
  pokemon.onHurt(_deltaHP => {
    let newHealthPercent = Pokemon$Skirmish.getHealthPercentage(pokemon);
    setHealth(healthbar, newHealthPercent);
  });
  return healthbar;
}

export {
  good,
  middle,
  bad,
  getHealthColor,
  setHealth,
  draw,
  make,
}
/*  Not a pure module */
