// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pos$Kaplay from "@nojaf/rescript-kaplay/src/Components/Pos.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.mjs";
import * as Pokemon$Skirmish from "./Pokemon.res.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.mjs";
import * as MetaData$Skirmish from "./MetaData.res.mjs";
import * as PkmnFont$Skirmish from "./PkmnFont.res.mjs";
import * as GameContext$Skirmish from "./GameContext.res.mjs";

Pos$Kaplay.Comp({});

let good = GameContext$Skirmish.k.Color.fromHex("#00bc7d");

let middle = GameContext$Skirmish.k.Color.fromHex("#ffdf20");

let bad = GameContext$Skirmish.k.Color.fromHex("#e7000b");

function getHealthColor(healthPercent) {
  if (healthPercent >= 60) {
    let t = (100 - healthPercent) / (100 - 60);
    return good.lerp(middle, t);
  }
  if (healthPercent < 20) {
    return bad;
  }
  let t$1 = (60 - healthPercent) / (60 - 20);
  return middle.lerp(bad, t$1);
}

function setHealth(healthbar, targetPercent) {
  let controller = healthbar.tweenControllerRef;
  if (controller !== undefined) {
    controller.cancel();
  }
  let controller$1 = GameContext$Skirmish.k.tween(healthbar.healthPercentage, targetPercent, 0.33, value => {
    healthbar.healthPercentage = value;
  }, GameContext$Skirmish.k.easings.easeOutSine);
  controller$1.onEnd(() => {
    healthbar.tweenControllerRef = undefined;
  });
  healthbar.tweenControllerRef = controller$1;
}

let cellHeight = 12 + 11 + 6 * 3;

let cellBgLight = "#fafaf9";

let cellBgDark = "#f3f4f6";

let cellCooldownBg = "#94a3b8";

let playerHeight = 3 * 2 + cellHeight * 2;

let Layout = {
  moveGridPaddingX: 3,
  moveGridPaddingY: 3,
  moveGridGap: 3,
  ppFontSize: 12,
  moveNameFontSize: 11,
  moveLineSpacing: 6,
  cellHeight: cellHeight,
  cellPaddingX: 8,
  numRows: 2,
  emptySlotFontSize: 8,
  cellBgLight: cellBgLight,
  cellBgDark: cellBgDark,
  cellCooldownBg: cellCooldownBg,
  movesSectionRatio: 0.7,
  nameHpSectionRatio: 0.3,
  nameFontSize: 12,
  levelFontSize: 10,
  hpBarHeight: 8,
  hpLabelWidth: 22,
  hpLabelFontSize: 8,
  sectionSpacing: 4,
  nameHpPaddingX: 5,
  separatorWidth: 2,
  playerHeight: playerHeight
};

let OpponentLayout = {
  paddingX: 5,
  lineY: 40,
  lineWidth: 2,
  nameFontSize: 14,
  nameY: 0,
  levelFontSize: 10,
  levelX: 70,
  levelY: 16,
  hpLabelFontSize: 8,
  hpLabelX: 5,
  hpLabelY: 28,
  hpBarX: 30,
  hpBarY: 30,
  hpBarWidth: 100,
  hpBarHeight: 5,
  height: 60
};

let keyLabels = [
  "j",
  "k",
  "l",
  ";"
];

function drawMove(slot, keyLabel, x, y, cellWidth, cellHeight) {
  let centerX = x + cellWidth / 2;
  let centerY = y + cellHeight / 2;
  let totalContentHeight = 12 + 11 + 6;
  let ppY = centerY - totalContentHeight / 2 + 12 / 2;
  let nameY = centerY + totalContentHeight / 2 - 11 / 2;
  if (slot.move.id === -1) {
    GameContext$Skirmish.k.drawText({
      pos: GameContext$Skirmish.k.vec2(centerX, centerY),
      color: GameContext$Skirmish.k.Color.fromHex("#9ca3af"),
      text: "(" + keyLabel + ") ---",
      font: Primitive_option.some(PkmnFont$Skirmish.font),
      size: 8,
      anchor: "center"
    });
    return;
  }
  let hotkeyText = "(" + keyLabel.toUpperCase() + ")";
  let ppFractionText = slot.currentPP.toString() + "/" + slot.move.maxPP.toString();
  GameContext$Skirmish.k.drawText({
    pos: GameContext$Skirmish.k.vec2(x + 8, ppY),
    color: GameContext$Skirmish.k.BLACK,
    text: hotkeyText,
    font: Primitive_option.some(PkmnFont$Skirmish.font),
    size: 12,
    anchor: "left"
  });
  GameContext$Skirmish.k.drawText({
    pos: GameContext$Skirmish.k.vec2(x + cellWidth - 8, ppY),
    color: slot.currentPP > 0 ? GameContext$Skirmish.k.BLACK : bad,
    text: ppFractionText,
    font: Primitive_option.some(PkmnFont$Skirmish.font),
    size: 12,
    anchor: "right"
  });
  GameContext$Skirmish.k.drawText({
    pos: GameContext$Skirmish.k.vec2(centerX, nameY),
    color: GameContext$Skirmish.k.BLACK,
    text: slot.move.name,
    font: Primitive_option.some(PkmnFont$Skirmish.font),
    size: 11,
    anchor: "center"
  });
}

function drawMoves(healthbar, movesWidth) {
  let pokemon = healthbar.pokemon;
  let moveSlots = [
    pokemon.moveSlot1,
    pokemon.moveSlot2,
    pokemon.moveSlot3,
    pokemon.moveSlot4
  ];
  let cellWidth = (movesWidth - 3 * 2 - 3) / 2;
  let cellHeight$1 = (cellHeight * 2 - 3) / 2;
  let debugColors = [
    "#ff0000",
    "#00ff00",
    "#0000ff",
    "#ffff00"
  ];
  let bgLight = GameContext$Skirmish.k.Color.fromHex(cellBgLight);
  let bgDark = GameContext$Skirmish.k.Color.fromHex(cellBgDark);
  let cooldownBg = GameContext$Skirmish.k.Color.fromHex(cellCooldownBg);
  let currentTime = GameContext$Skirmish.k.time();
  moveSlots.forEach((slot, index) => {
    let col = index % 2;
    let row = index / 2 | 0;
    let x = 3 + col * (cellWidth + 3);
    let y = 3 + row * (cellHeight$1 + 3);
    let bgColor = index === 0 || index === 3 ? bgDark : bgLight;
    GameContext$Skirmish.k.drawRect({
      pos: GameContext$Skirmish.k.vec2(x, y),
      color: bgColor,
      width: cellWidth,
      height: cellHeight$1
    });
    if (slot.move.id !== -1 && slot.move.coolDownDuration > 0) {
      let timeSinceUse = currentTime - slot.lastUsedAt;
      let cooldownRemaining = slot.move.coolDownDuration - timeSinceUse;
      if (cooldownRemaining > 0) {
        let cooldownProgress = cooldownRemaining / slot.move.coolDownDuration;
        let overlayWidth = cellWidth * cooldownProgress;
        GameContext$Skirmish.k.drawRect({
          pos: GameContext$Skirmish.k.vec2(x, y),
          color: cooldownBg,
          opacity: 0.5,
          width: overlayWidth,
          height: cellHeight$1
        });
      }
    }
    if (GameContext$Skirmish.k.debug.inspect) {
      let debugColor = Stdlib_Option.getOr(debugColors[index], "#000000");
      GameContext$Skirmish.k.drawRect({
        pos: GameContext$Skirmish.k.vec2(x, y),
        color: GameContext$Skirmish.k.Color.fromHex(debugColor),
        opacity: 0.3,
        width: cellWidth,
        height: cellHeight$1
      });
    }
    let keyLabel = Stdlib_Option.getOr(keyLabels[index], "?");
    drawMove(slot, keyLabel, x, y, cellWidth, cellHeight$1);
  });
}

function draw() {
  let healthbar = this ;
  if (healthbar.team === true) {
    let totalWidth = GameContext$Skirmish.k.width();
    let movesWidth = totalWidth * 0.7;
    let nameHpWidth = totalWidth * 0.3;
    let nameHpCenterX = movesWidth + nameHpWidth / 2;
    if (GameContext$Skirmish.k.debug.inspect) {
      GameContext$Skirmish.k.drawRect({
        pos: GameContext$Skirmish.k.vec2(0, 0),
        color: GameContext$Skirmish.k.Color.fromHex("#ff0000"),
        opacity: 0.2,
        width: movesWidth,
        height: playerHeight
      });
      GameContext$Skirmish.k.drawRect({
        pos: GameContext$Skirmish.k.vec2(movesWidth, 0),
        color: GameContext$Skirmish.k.Color.fromHex("#0000ff"),
        opacity: 0.2,
        width: nameHpWidth,
        height: playerHeight
      });
    }
    drawMoves(healthbar, movesWidth);
    GameContext$Skirmish.k.drawLine({
      p1: GameContext$Skirmish.k.vec2(movesWidth, 0),
      p2: GameContext$Skirmish.k.vec2(movesWidth, playerHeight),
      width: 2,
      color: GameContext$Skirmish.k.BLACK
    });
    let totalContentHeight = 12 + 10 + 8 + 4 * 2;
    let contentStartY = (playerHeight - totalContentHeight) / 2;
    let nameY = contentStartY + 12 / 2;
    let levelY = nameY + 12 / 2 + 4 + 10 / 2;
    let hpY = levelY + 10 / 2 + 4;
    GameContext$Skirmish.k.drawText({
      pos: GameContext$Skirmish.k.vec2(nameHpCenterX, nameY),
      color: GameContext$Skirmish.k.BLACK,
      text: healthbar.name.toUpperCase(),
      font: Primitive_option.some(PkmnFont$Skirmish.font),
      size: 12,
      letterSpacing: 0.5,
      anchor: "center"
    });
    GameContext$Skirmish.k.drawText({
      pos: GameContext$Skirmish.k.vec2(nameHpCenterX, levelY),
      color: GameContext$Skirmish.k.BLACK,
      text: ":L" + healthbar.level.toString(),
      font: Primitive_option.some(PkmnFont$Skirmish.font),
      size: 10,
      anchor: "center"
    });
    let hpBarWidth = nameHpWidth - 5 * 2 - 22;
    let hpStartX = movesWidth + 5;
    GameContext$Skirmish.k.drawText({
      pos: GameContext$Skirmish.k.vec2(hpStartX, hpY),
      color: GameContext$Skirmish.k.BLACK,
      text: "HP:",
      font: Primitive_option.some(PkmnFont$Skirmish.font),
      size: 8
    });
    GameContext$Skirmish.k.drawRect({
      pos: GameContext$Skirmish.k.vec2(hpStartX + 22, hpY + 2),
      color: GameContext$Skirmish.k.Color.fromHex("#e5e7eb"),
      outline: {
        width: 2,
        color: GameContext$Skirmish.k.BLACK
      },
      width: hpBarWidth,
      height: 8,
      radius: [
        3,
        3,
        3,
        3
      ]
    });
    let healthColor = getHealthColor(healthbar.healthPercentage);
    let healthWidth = healthbar.healthPercentage / 100 * hpBarWidth;
    GameContext$Skirmish.k.drawRect({
      pos: GameContext$Skirmish.k.vec2(hpStartX + 22, hpY + 2),
      color: healthColor,
      width: healthWidth,
      height: 8,
      radius: [
        3,
        0,
        0,
        3
      ]
    });
    return;
  }
  let lines = [
    GameContext$Skirmish.k.Vec2.ZERO,
    GameContext$Skirmish.k.vec2(0, 40),
    GameContext$Skirmish.k.vec2(GameContext$Skirmish.k.width() / 2, 40)
  ];
  GameContext$Skirmish.k.drawLines({
    pts: lines,
    color: GameContext$Skirmish.k.BLACK,
    width: 2
  });
  GameContext$Skirmish.k.drawText({
    pos: GameContext$Skirmish.k.vec2(5, 0),
    color: GameContext$Skirmish.k.BLACK,
    text: healthbar.name.toUpperCase(),
    font: Primitive_option.some(PkmnFont$Skirmish.font),
    size: 14,
    letterSpacing: 0.5
  });
  GameContext$Skirmish.k.drawText({
    pos: GameContext$Skirmish.k.vec2(70, 16),
    color: GameContext$Skirmish.k.BLACK,
    text: ":L" + healthbar.level.toString(),
    font: Primitive_option.some(PkmnFont$Skirmish.font),
    size: 10
  });
  GameContext$Skirmish.k.drawText({
    pos: GameContext$Skirmish.k.vec2(5, 28),
    color: GameContext$Skirmish.k.BLACK,
    text: "HP:",
    font: Primitive_option.some(PkmnFont$Skirmish.font),
    size: 8
  });
  GameContext$Skirmish.k.drawRect({
    pos: GameContext$Skirmish.k.vec2(30, 30),
    color: GameContext$Skirmish.k.Color.fromHex("#e5e7eb"),
    outline: {
      width: 2,
      color: GameContext$Skirmish.k.BLACK
    },
    width: 100,
    height: 5,
    radius: [
      3,
      3,
      3,
      3
    ]
  });
  let healthColor$1 = getHealthColor(healthbar.healthPercentage);
  let healthWidth$1 = healthbar.healthPercentage / 100 * 100;
  GameContext$Skirmish.k.drawRect({
    pos: GameContext$Skirmish.k.vec2(30, 30),
    color: healthColor$1,
    width: healthWidth$1,
    height: 5,
    radius: [
      3,
      0,
      0,
      3
    ]
  });
}

function make(pokemon) {
  let healthbar = GameContext$Skirmish.k.add([
    {
      healthPercentage: Pokemon$Skirmish.getHealthPercentage(pokemon),
      name: Stdlib_Option.getOr(MetaData$Skirmish.names.get(pokemon.pokemonId), "???"),
      level: pokemon.level,
      team: Pokemon$Skirmish.getTeam(pokemon),
      pokemon: pokemon
    },
    {
      id: "healthbar",
      draw: draw
    },
    Pokemon$Skirmish.getTeam(pokemon) === false ? GameContext$Skirmish.k.pos(10, 10) : GameContext$Skirmish.k.pos(0, GameContext$Skirmish.k.height() - playerHeight)
  ]);
  pokemon.onHurt(_deltaHP => {
    let newHealthPercent = Pokemon$Skirmish.getHealthPercentage(pokemon);
    setHealth(healthbar, newHealthPercent);
  });
  return healthbar;
}

let middleUpperLimit = 60;

let middleLowerLimit = 20;

export {
  good,
  middle,
  bad,
  middleUpperLimit,
  middleLowerLimit,
  getHealthColor,
  setHealth,
  Layout,
  OpponentLayout,
  keyLabels,
  drawMove,
  drawMoves,
  draw,
  make,
}
/*  Not a pure module */
