// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pos$Kaplay from "@nojaf/rescript-kaplay/src/Components/Pos.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Pokemon$Skirmish from "./Pokemon.res.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as MetaData$Skirmish from "./MetaData.res.mjs";
import * as PkmnFont$Skirmish from "./PkmnFont.res.mjs";
import * as GameContext$Skirmish from "./GameContext.res.mjs";

Pos$Kaplay.Comp({});

let good = GameContext$Skirmish.k.Color.fromHex("#00bc7d");

let middle = GameContext$Skirmish.k.Color.fromHex("#ffdf20");

let bad = GameContext$Skirmish.k.Color.fromHex("#e7000b");

function getHealthColor(healthPercent) {
  if (healthPercent >= 60) {
    let t = (100 - healthPercent) / (100 - 60);
    return good.lerp(middle, t);
  }
  if (healthPercent < 20) {
    return bad;
  }
  let t$1 = (60 - healthPercent) / (60 - 20);
  return middle.lerp(bad, t$1);
}

function setHealth(healthbar, targetPercent) {
  let controller = healthbar.tweenControllerRef;
  if (controller !== undefined) {
    controller.cancel();
  }
  let controller$1 = GameContext$Skirmish.k.tween(healthbar.healthPercentage, targetPercent, 0.33, value => {
    healthbar.healthPercentage = value;
  }, GameContext$Skirmish.k.easings.easeOutSine);
  controller$1.onEnd(() => {
    healthbar.tweenControllerRef = undefined;
  });
  healthbar.tweenControllerRef = controller$1;
}

function draw() {
  let healthbar = this ;
  let lines = healthbar.team === false ? [
      GameContext$Skirmish.k.Vec2.ZERO,
      GameContext$Skirmish.k.vec2(0, 40),
      GameContext$Skirmish.k.vec2(GameContext$Skirmish.k.width() / 2, 40)
    ] : [
      GameContext$Skirmish.k.vec2(GameContext$Skirmish.k.width() / 2, 0),
      GameContext$Skirmish.k.vec2(GameContext$Skirmish.k.width() / 2, 40),
      GameContext$Skirmish.k.vec2(0, 40)
    ];
  GameContext$Skirmish.k.drawLines({
    pts: lines,
    color: GameContext$Skirmish.k.BLACK,
    width: 2
  });
  GameContext$Skirmish.k.drawText({
    pos: GameContext$Skirmish.k.vec2(5, 0),
    color: GameContext$Skirmish.k.BLACK,
    text: healthbar.name.toUpperCase(),
    font: Primitive_option.some(PkmnFont$Skirmish.name),
    size: 10,
    letterSpacing: 0.5
  });
  GameContext$Skirmish.k.drawText({
    pos: GameContext$Skirmish.k.vec2(70, 12),
    color: GameContext$Skirmish.k.BLACK,
    text: ":L" + healthbar.level.toString(),
    font: Primitive_option.some(PkmnFont$Skirmish.name),
    size: 10
  });
  GameContext$Skirmish.k.drawText({
    pos: GameContext$Skirmish.k.vec2(5, 25),
    color: GameContext$Skirmish.k.BLACK,
    text: "HP:",
    font: Primitive_option.some(PkmnFont$Skirmish.name),
    size: 6
  });
  GameContext$Skirmish.k.drawRect({
    pos: GameContext$Skirmish.k.vec2(25, 25),
    color: GameContext$Skirmish.k.Color.fromHex("#e5e7eb"),
    outline: {
      width: 1,
      color: GameContext$Skirmish.k.BLACK
    },
    width: 100,
    height: 5,
    radius: [
      3,
      3,
      3,
      3
    ]
  });
  let animatedPercent = healthbar.healthPercentage;
  let healthColor = getHealthColor(animatedPercent);
  let healthbarWidth = healthbar.healthPercentage;
  GameContext$Skirmish.k.drawRect({
    pos: GameContext$Skirmish.k.vec2(25, 25),
    color: healthColor,
    width: healthbarWidth,
    height: 5,
    radius: [
      3,
      0,
      0,
      3
    ]
  });
}

function make(pokemon) {
  let healthbar = GameContext$Skirmish.k.add([
    {
      healthPercentage: Pokemon$Skirmish.getHealthPercentage(pokemon),
      name: Stdlib_Option.getOr(MetaData$Skirmish.names.get(pokemon.pokemonId), "???"),
      level: pokemon.level,
      team: pokemon.team
    },
    {
      id: "healthbar",
      draw: draw
    },
    pokemon.team === false ? GameContext$Skirmish.k.pos(10, 10) : GameContext$Skirmish.k.pos(GameContext$Skirmish.k.width() / 2 - 10, GameContext$Skirmish.k.height() - 50)
  ]);
  pokemon.onHurt(_deltaHP => {
    let newHealthPercent = Pokemon$Skirmish.getHealthPercentage(pokemon);
    setHealth(healthbar, newHealthPercent);
  });
  return healthbar;
}

let middleUpperLimit = 60;

let middleLowerLimit = 20;

export {
  good,
  middle,
  bad,
  middleUpperLimit,
  middleLowerLimit,
  getHealthColor,
  setHealth,
  draw,
  make,
}
/*  Not a pure module */
