// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Game$Skirmish from "./Game.res.mjs";
import * as GameOver$Skirmish from "./GameOver.res.mjs";
import * as GameContext$Skirmish from "./GameContext.res.mjs";

GameContext$Skirmish.k.scene("game", Game$Skirmish.scene);

GameContext$Skirmish.k.scene(GameOver$Skirmish.sceneName, GameOver$Skirmish.scene);

GameContext$Skirmish.k.go("game");

/*  Not a pure module */
