// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pervasives from "@rescript/runtime/lib/es6/Pervasives.js";

function makeMoveSlot(move) {
  return {
    move: move,
    currentPP: move.maxPP,
    lastUsedAt: Pervasives.neg_infinity
  };
}

export {
  makeMoveSlot,
}
/* No side effect */
