// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pervasives from "@rescript/runtime/lib/es6/Pervasives.mjs";

function makeMoveSlot(move) {
  return {
    move: move,
    currentPP: move.maxPP,
    lastUsedAt: Pervasives.neg_infinity
  };
}

function canCast(slot, currentTime) {
  if (slot.currentPP > 0 && slot.move.id !== -1) {
    return currentTime - slot.lastUsedAt >= slot.move.coolDownDuration;
  } else {
    return false;
  }
}

function defaultAddRulesForAI(k, rs, moveSlot, factNames) {
  rs.addRuleExecutingAction(_rs => {
    let currentTime = k.time();
    return canCast(moveSlot, currentTime);
  }, rs => {
    rs.assertFact(factNames.available);
  }, 25.0);
}

let move0Facts = {
  available: "move-0-available",
  successRate: "move-0-success-rate"
};

let move1Facts = {
  available: "move-1-available",
  successRate: "move-1-success-rate"
};

let move2Facts = {
  available: "move-2-available",
  successRate: "move-2-success-rate"
};

let move3Facts = {
  available: "move-3-available",
  successRate: "move-3-success-rate"
};

export {
  move0Facts,
  move1Facts,
  move2Facts,
  move3Facts,
  makeMoveSlot,
  canCast,
  defaultAddRulesForAI,
}
/* No side effect */
