// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pervasives from "@rescript/runtime/lib/es6/Pervasives.mjs";

function makeMoveSlot(move) {
  return {
    move: move,
    currentPP: move.maxPP,
    lastUsedAt: Pervasives.neg_infinity
  };
}

function canCast(slot, currentTime) {
  if (slot.currentPP > 0 && slot.move.id !== -1) {
    return currentTime - slot.lastUsedAt >= slot.move.coolDownDuration;
  } else {
    return false;
  }
}

export {
  makeMoveSlot,
  canCast,
}
/* No side effect */
