// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pokemon$Skirmish from "./Pokemon.res.mjs";
import * as GameContext$Skirmish from "./GameContext.res.mjs";

function make(pokemonId, level) {
  let gameObj = Pokemon$Skirmish.make(pokemonId, level, "Player");
  GameContext$Skirmish.k.onKeyRelease(key => {
    
  });
  return gameObj;
}

export {
  make,
}
/* Pokemon-Skirmish Not a pure module */
