// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pokemon$Skirmish from "./Pokemon.res.mjs";
import * as GameContext$Skirmish from "./GameContext.res.mjs";

function make(pokemon) {
  let spaceWasDown = {
    contents: false
  };
  GameContext$Skirmish.k.onUpdate(() => {
    let isSpacePressed = GameContext$Skirmish.k.isKeyDown("space");
    let isNewSpacePress = isSpacePressed && !spaceWasDown.contents;
    spaceWasDown.contents = isSpacePressed;
    let isUpPressed = GameContext$Skirmish.k.isKeyDown("up") || GameContext$Skirmish.k.isKeyDown("w");
    let isDownPressed = GameContext$Skirmish.k.isKeyDown("down") || GameContext$Skirmish.k.isKeyDown("s");
    let isLeftPressed = GameContext$Skirmish.k.isKeyDown("left") || GameContext$Skirmish.k.isKeyDown("a");
    let isRightPressed = GameContext$Skirmish.k.isKeyDown("right") || GameContext$Skirmish.k.isKeyDown("d");
    let movementPressed = isUpPressed || isDownPressed || isLeftPressed || isRightPressed;
    if (isNewSpacePress) {
      Pokemon$Skirmish.tryCastMove(GameContext$Skirmish.k, pokemon, 0);
    } else if (isUpPressed) {
      pokemon.direction = GameContext$Skirmish.k.Vec2.UP;
      pokemon.sprite = Pokemon$Skirmish.backSpriteName(pokemon.pokemonId);
    } else if (isDownPressed) {
      pokemon.direction = GameContext$Skirmish.k.Vec2.DOWN;
      pokemon.sprite = Pokemon$Skirmish.frontSpriteName(pokemon.pokemonId);
    } else if (isLeftPressed) {
      pokemon.direction = GameContext$Skirmish.k.Vec2.LEFT;
    } else if (isRightPressed) {
      pokemon.direction = GameContext$Skirmish.k.Vec2.RIGHT;
    }
    if (pokemon.mobility === true && movementPressed) {
      pokemon.move(pokemon.direction.scale(Pokemon$Skirmish.movementSpeed));
      return;
    }
  });
}

export {
  make,
}
/* Pokemon-Skirmish Not a pure module */
