// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pos$Kaplay from "@nojaf/rescript-kaplay/src/Components/Pos.res.mjs";
import * as Area$Kaplay from "@nojaf/rescript-kaplay/src/Components/Area.res.mjs";
import * as Body$Kaplay from "@nojaf/rescript-kaplay/src/Components/Body.res.mjs";
import * as Anchor$Kaplay from "@nojaf/rescript-kaplay/src/Components/Anchor.res.mjs";
import * as Health$Kaplay from "@nojaf/rescript-kaplay/src/Components/Health.res.mjs";
import * as Shader$Kaplay from "@nojaf/rescript-kaplay/src/Components/Shader.res.mjs";
import * as Sprite$Kaplay from "@nojaf/rescript-kaplay/src/Components/Sprite.res.mjs";
import * as Team$Skirmish from "./Team.res.mjs";
import * as Animate$Kaplay from "@nojaf/rescript-kaplay/src/Components/Animate.res.mjs";
import * as Opacity$Kaplay from "@nojaf/rescript-kaplay/src/Components/Opacity.res.mjs";
import * as GameObjRaw$Kaplay from "@nojaf/rescript-kaplay/src/Components/GameObjRaw.res.mjs";

GameObjRaw$Kaplay.Comp({});

Pos$Kaplay.Comp({});

Sprite$Kaplay.Comp({});

Area$Kaplay.Comp({});

Health$Kaplay.Comp({});

Anchor$Kaplay.Comp({});

Shader$Kaplay.Comp({});

Opacity$Kaplay.Comp({});

Animate$Kaplay.Comp({});

Body$Kaplay.Comp({});

let tag = "pokemon";

function frontSpriteName(id) {
  return "pokemon-" + id.toString() + "-front";
}

function backSpriteName(id) {
  return "pokemon-" + id.toString() + "-back";
}

function frontSpriteUrl(id) {
  return `/sprites/` + id.toString() + `-front.png`;
}

function backSpriteUrl(id) {
  return `/sprites/` + id.toString() + `-back.png`;
}

function load(k, id) {
  k.loadSprite(frontSpriteName(id), frontSpriteUrl(id), {
    singular: true
  });
  k.loadSprite(backSpriteName(id), backSpriteUrl(id), {
    singular: true
  });
}

function getHealthPercentage(pokemon) {
  let currentHp = pokemon.hp;
  let maxHp = pokemon.maxHP;
  return currentHp / maxHp * 100;
}

function moveLeft(k, pokemon) {
  pokemon.move(k.vec2(-100, 0));
}

function moveRight(k, pokemon) {
  pokemon.move(k.vec2(100, 0));
}

function make(k, pokemonId, level, team) {
  let match = team === true ? [
      backSpriteName(pokemonId),
      k.Vec2.UP,
      k.height() * 0.75
    ] : [
      frontSpriteName(pokemonId),
      k.Vec2.DOWN,
      k.height() * 0.25
    ];
  let sprite = k.getSprite(match[0]).data;
  let match$1;
  if (sprite === null) {
    match$1 = [
      0,
      0
    ];
  } else {
    let halfSize = sprite.width / 2;
    let squaredPersonalSpace = halfSize * halfSize * halfSize;
    match$1 = [
      halfSize,
      squaredPersonalSpace
    ];
  }
  let gameObj = k.add([
    {
      direction: match[1],
      facing: true,
      mobility: true,
      attackStatus: true,
      level: level,
      pokemonId: pokemonId,
      team: team,
      halfSize: match$1[0],
      squaredPersonalSpace: match$1[1]
    },
    k.pos(k.center().x, match[2]),
    k.sprite(frontSpriteName(pokemonId)),
    team === true ? Team$Skirmish.playerTagComponent : Team$Skirmish.opponentTagComponent,
    k.area(),
    k.body(),
    k.health(20, 20),
    k.anchor("center"),
    k.opacity(1),
    k.animate(),
    tag,
    {
      id: "pokemon",
      drawInspect: function () {
        let gameObj = this ;
        let radius = Math.sqrt(gameObj.squaredPersonalSpace);
        k.drawCircle({
          opacity: 0.1,
          outline: {
            width: 2,
            color: k.MAGENTA
          },
          radius: radius
        });
      }
    }
  ]);
  gameObj.onHurt(deltaHp => {
    console.log("I hurt myself today", deltaHp);
    gameObj.unanimate("opacity");
    let animation = gameObj.animation;
    animation.seek(0);
    gameObj.animate("opacity", [
      1,
      0.3,
      1,
      0.5,
      1
    ], {
      duration: 0.4,
      loops: 1
    });
  });
  return gameObj;
}

let movementSpeed = 200;

export {
  tag,
  frontSpriteName,
  backSpriteName,
  frontSpriteUrl,
  backSpriteUrl,
  load,
  movementSpeed,
  getHealthPercentage,
  moveLeft,
  moveRight,
  make,
}
/*  Not a pure module */
