// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Pos$Kaplay from "@nojaf/rescript-kaplay/src/Components/Pos.res.mjs";
import * as Area$Kaplay from "@nojaf/rescript-kaplay/src/Components/Area.res.mjs";
import * as Anchor$Kaplay from "@nojaf/rescript-kaplay/src/Components/Anchor.res.mjs";
import * as Health$Kaplay from "@nojaf/rescript-kaplay/src/Components/Health.res.mjs";
import * as Shader$Kaplay from "@nojaf/rescript-kaplay/src/Components/Shader.res.mjs";
import * as Sprite$Kaplay from "@nojaf/rescript-kaplay/src/Components/Sprite.res.mjs";
import * as Team$Skirmish from "./Team.res.mjs";
import * as Animate$Kaplay from "@nojaf/rescript-kaplay/src/Components/Animate.res.mjs";
import * as Opacity$Kaplay from "@nojaf/rescript-kaplay/src/Components/Opacity.res.mjs";
import * as GameObjRaw$Kaplay from "@nojaf/rescript-kaplay/src/Components/GameObjRaw.res.mjs";

GameObjRaw$Kaplay.Comp({});

Pos$Kaplay.Comp({});

Sprite$Kaplay.Comp({});

Area$Kaplay.Comp({});

Health$Kaplay.Comp({});

Anchor$Kaplay.Comp({});

Shader$Kaplay.Comp({});

Opacity$Kaplay.Comp({});

Animate$Kaplay.Comp({});

let tag = "pokemon";

function frontSpriteName(id) {
  return "pokemon-" + id.toString() + "-front";
}

function backSpriteName(id) {
  return "pokemon-" + id.toString() + "-back";
}

function frontSpriteUrl(id) {
  return `/sprites/` + id.toString() + `-front.png`;
}

function backSpriteUrl(id) {
  return `/sprites/` + id.toString() + `-back.png`;
}

function load(k, id) {
  k.loadSprite(frontSpriteName(id), frontSpriteUrl(id), {
    singular: true
  });
  k.loadSprite(backSpriteName(id), backSpriteUrl(id), {
    singular: true
  });
}

function getHealthPercentage(pokemon) {
  let currentHp = pokemon.hp;
  let maxHp = pokemon.maxHP;
  return currentHp / maxHp * 100;
}

function make(k, pokemonId, level, team) {
  let gameObj = k.add(Belt_Array.concatMany([
    team === true ? [
        {
          direction: k.Vec2.UP,
          facing: true,
          mobility: true,
          attackStatus: true,
          level: level,
          pokemonId: pokemonId,
          team: team
        },
        k.pos(k.center().x, k.height() * 0.8),
        k.sprite(backSpriteName(pokemonId)),
        Team$Skirmish.playerTagComponent
      ] : [
        {
          direction: k.Vec2.DOWN,
          facing: false,
          mobility: true,
          attackStatus: true,
          level: level,
          pokemonId: pokemonId,
          team: team
        },
        k.pos(k.center().x, k.height() * 0.2),
        k.sprite(frontSpriteName(pokemonId)),
        Team$Skirmish.opponentTagComponent
      ],
    [
      k.area(),
      k.health(20, 20),
      k.anchor("center"),
      k.opacity(1),
      k.animate(),
      tag
    ]
  ]));
  gameObj.onHurt(deltaHp => {
    console.log("I hurt myself today", deltaHp);
    gameObj.unanimate("opacity");
    let animation = gameObj.animation;
    animation.seek(0);
    gameObj.animate("opacity", [
      1,
      0.3,
      1,
      0.5,
      1
    ], {
      duration: 0.4,
      loops: 1
    });
  });
  return gameObj;
}

let movementSpeed = 200;

export {
  tag,
  frontSpriteName,
  backSpriteName,
  frontSpriteUrl,
  backSpriteUrl,
  load,
  movementSpeed,
  getHealthPercentage,
  make,
}
/*  Not a pure module */
