// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pos$Kaplay from "@nojaf/rescript-kaplay/src/Components/Pos.res.mjs";
import * as Area$Kaplay from "@nojaf/rescript-kaplay/src/Components/Area.res.mjs";
import * as Anchor$Kaplay from "@nojaf/rescript-kaplay/src/Components/Anchor.res.mjs";
import * as Health$Kaplay from "@nojaf/rescript-kaplay/src/Components/Health.res.mjs";
import * as Shader$Kaplay from "@nojaf/rescript-kaplay/src/Components/Shader.res.mjs";
import * as Sprite$Kaplay from "@nojaf/rescript-kaplay/src/Components/Sprite.res.mjs";
import * as GameObjRaw$Kaplay from "@nojaf/rescript-kaplay/src/Components/GameObjRaw.res.mjs";
import * as GameContext$Skirmish from "./GameContext.res.mjs";
import * as Thundershock$Skirmish from "./Thundershock.res.mjs";

GameObjRaw$Kaplay.Comp({});

Pos$Kaplay.Comp({});

Sprite$Kaplay.Comp({});

Area$Kaplay.Comp({});

Health$Kaplay.Comp({});

Anchor$Kaplay.Comp({});

Shader$Kaplay.Comp({});

let tag = "pokemon";

function frontSpriteName(id) {
  return "pokemon-" + id.toString() + "-front";
}

function backSpriteName(id) {
  return "pokemon-" + id.toString() + "-back";
}

function frontSpriteUrl(id) {
  return `/sprites/` + id.toString() + `-front.png`;
}

function backSpriteUrl(id) {
  return `/sprites/` + id.toString() + `-back.png`;
}

function load(id) {
  GameContext$Skirmish.k.loadSprite(frontSpriteName(id), frontSpriteUrl(id), {
    singular: true
  });
  GameContext$Skirmish.k.loadSprite(backSpriteName(id), backSpriteUrl(id), {
    singular: true
  });
}

function make(id) {
  let gameObj = GameContext$Skirmish.k.add([
    {
      direction: GameContext$Skirmish.k.Vec2.UP
    },
    GameContext$Skirmish.k.pos(GameContext$Skirmish.k.center().x, GameContext$Skirmish.k.height() * 0.8),
    GameContext$Skirmish.k.sprite(backSpriteName(id)),
    GameContext$Skirmish.k.area(),
    GameContext$Skirmish.k.health(20),
    GameContext$Skirmish.k.anchor("center"),
    tag
  ]);
  GameContext$Skirmish.k.onUpdate(() => {
    let leftDown = GameContext$Skirmish.k.isKeyDown("left") || GameContext$Skirmish.k.isKeyDown("a");
    let rightDown = GameContext$Skirmish.k.isKeyDown("right") || GameContext$Skirmish.k.isKeyDown("d");
    let upDown = GameContext$Skirmish.k.isKeyDown("up") || GameContext$Skirmish.k.isKeyDown("w");
    let downDown = GameContext$Skirmish.k.isKeyDown("down") || GameContext$Skirmish.k.isKeyDown("s");
    if (leftDown || rightDown || upDown || downDown) {
      if (upDown && !downDown) {
        gameObj.direction = GameContext$Skirmish.k.Vec2.UP;
        gameObj.sprite = backSpriteName(id);
      } else if (downDown && !upDown) {
        gameObj.direction = GameContext$Skirmish.k.Vec2.DOWN;
        gameObj.sprite = frontSpriteName(id);
      } else if (leftDown && !rightDown) {
        gameObj.direction = GameContext$Skirmish.k.Vec2.LEFT;
      } else if (rightDown && !leftDown) {
        gameObj.direction = GameContext$Skirmish.k.Vec2.RIGHT;
      }
      gameObj.move(gameObj.direction.scale(200));
      return;
    }
  });
  GameContext$Skirmish.k.onKeyRelease(key => {
    if (key !== "f1" && key !== "shift" && key !== "f2" && key !== "down" && key !== "f3" && key !== "up" && key !== "f4" && key !== "right" && key !== "f5" && key !== "left" && key !== "f6" && key !== " " && key !== "f7" && key !== "space" && key !== "f8" && key !== "meta" && key !== "f9" && key !== "alt" && key !== "f10" && key !== "control" && key !== "f11" && key !== "tab" && key !== "f12" && key !== "enter" && key !== "`" && key !== "backspace" && key !== "1" && key !== "escape" && key !== "2" && key !== "/" && key !== "3" && key !== "." && key !== "4" && key !== "," && key !== "5" && key !== "m" && key !== "6" && key !== "n" && key !== "7" && key !== "b" && key !== "8" && key !== "v" && key !== "9" && key !== "c" && key !== "0" && key !== "x" && key !== "-" && key !== "z" && key !== "+" && key !== "'" && key !== "=" && key !== ";" && key !== "q" && key !== "l" && key !== "w" && key !== "k" && key !== "e" && key !== "j" && key !== "r" && key !== "h" && key !== "t" && key !== "g" && key !== "y" && key !== "f" && key !== "u" && key !== "d" && key !== "i" && key !== "s" && key !== "o" && key !== "a" && key !== "p" && key !== "\\" && key !== "[" && key !== "]") {
      return;
    }
    if (key !== "space") {
      return;
    }
    console.log("Triggering Thundershock");
    Thundershock$Skirmish.cast(gameObj);
  });
  return gameObj;
}

let movementSpeed = 200;

export {
  tag,
  frontSpriteName,
  backSpriteName,
  frontSpriteUrl,
  backSpriteUrl,
  load,
  movementSpeed,
  make,
}
/*  Not a pure module */
