// Generated by ReScript, PLEASE EDIT WITH CARE


let player = "player";

let opponent = "opponent";

let playerTagComponent = player;

let opponentTagComponent = opponent;

export {
  player,
  opponent,
  playerTagComponent,
  opponentTagComponent,
}
/* No side effect */
