// Generated by ReScript, PLEASE EDIT WITH CARE


let player = "player";

let opponent = "opponent";

function getTagComponent(team) {
  if (team === true) {
    return player;
  } else {
    return opponent;
  }
}

let playerTagComponent = player;

let opponentTagComponent = opponent;

export {
  player,
  opponent,
  playerTagComponent,
  opponentTagComponent,
  getTagComponent,
}
/* No side effect */
