// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Z$Kaplay from "@nojaf/rescript-kaplay/src/Components/Z.res.mjs";
import * as Pos$Kaplay from "@nojaf/rescript-kaplay/src/Components/Pos.res.mjs";
import * as Math$Kaplay from "@nojaf/rescript-kaplay/src/Math.res.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Anchor$Kaplay from "@nojaf/rescript-kaplay/src/Components/Anchor.res.mjs";
import * as GameObjRaw$Kaplay from "@nojaf/rescript-kaplay/src/Components/GameObjRaw.res.mjs";
import * as GameContext$Skirmish from "./GameContext.res.mjs";

Pos$Kaplay.Comp({});

Anchor$Kaplay.Comp({});

GameObjRaw$Kaplay.Comp({});

Z$Kaplay.Comp({});

let lighting = GameContext$Skirmish.k.Color.fromHex("#ffdf20");

let lighting2 = GameContext$Skirmish.k.Color.fromHex("#fee685");

function draw() {
  let t = this ;
  GameContext$Skirmish.k.drawLines({
    pts: t.points,
    color: lighting,
    width: 2,
    cap: "square"
  });
}

let worldRect = Math$Kaplay.Rect.make(GameContext$Skirmish.k, GameContext$Skirmish.k.Vec2.ZERO, GameContext$Skirmish.k.width(), GameContext$Skirmish.k.height());

function make(addToParent, origin, direction) {
  let direction$1 = direction.scale(20);
  console.log("Origin: ", origin, "Direction: ", direction$1);
  let gameObj = addToParent([
    {
      points: [GameContext$Skirmish.k.Vec2.ZERO]
    },
    GameContext$Skirmish.k.pos(0, 0),
    GameContext$Skirmish.k.z(-1),
    {
      id: "thundershock",
      draw: draw
    }
  ]);
  let timerRef = {
    contents: undefined
  };
  timerRef.contents = GameContext$Skirmish.k.loop(0.050, () => {
    let point = Stdlib_Array.last(gameObj.points);
    let lastPoint = point !== undefined ? point : GameContext$Skirmish.k.Vec2.ZERO;
    let deviation = GameContext$Skirmish.k.rand(-1 * 7, 7);
    let candidate = GameContext$Skirmish.k.vec2(deviation, lastPoint.y + direction$1.y);
    let candidateInWorldRect = gameObj.worldPos().add(candidate);
    if (worldRect.contains(candidateInWorldRect)) {
      gameObj.points.push(candidate);
      return;
    }
    candidateInWorldRect.x = GameContext$Skirmish.k.clamp(candidateInWorldRect.x, 0, GameContext$Skirmish.k.width());
    candidateInWorldRect.y = GameContext$Skirmish.k.clamp(candidateInWorldRect.y, 0, GameContext$Skirmish.k.height());
    let cappedLocal = candidateInWorldRect.sub(gameObj.worldPos());
    gameObj.points.push(cappedLocal);
    let t = timerRef.contents;
    if (t !== undefined) {
      t.cancel();
    }
    GameContext$Skirmish.k.wait(5 * 0.050, () => {
      gameObj.destroy();
    });
  });
}

let intervalSeconds = 0.050;

let deviationOffset = 7;

let distance = 20;

export {
  lighting,
  lighting2,
  draw,
  worldRect,
  intervalSeconds,
  deviationOffset,
  distance,
  make,
}
/*  Not a pure module */
