// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_float from "@rescript/runtime/lib/es6/Primitive_float.js";

let scale = Primitive_float.min(1.5, Primitive_float.min(window.innerWidth / 800, window.innerHeight / 400));

export {
  scale,
}
/* scale Not a pure module */
