// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pos$Kaplay from "@nojaf/rescript-kaplay/src/Components/Pos.res.mjs";
import * as Area$Kaplay from "@nojaf/rescript-kaplay/src/Components/Area.res.mjs";
import * as Text$Kaplay from "@nojaf/rescript-kaplay/src/Components/Text.res.mjs";
import * as Color$Kaplay from "@nojaf/rescript-kaplay/src/Components/Color.res.mjs";
import * as Anchor$Kaplay from "@nojaf/rescript-kaplay/src/Components/Anchor.res.mjs";
import * as Stdlib_Option from "rescript/lib/es6/Stdlib_Option.js";

Pos$Kaplay.Comp({});

Text$Kaplay.Comp({});

Color$Kaplay.Comp({});

Anchor$Kaplay.Comp({});

Area$Kaplay.Comp({});

function make(k, text, x, y, anchor, colorOpt, sizeOpt, action, hoverColor) {
  let color = colorOpt !== undefined ? colorOpt : "#000000";
  let size = sizeOpt !== undefined ? sizeOpt : 24;
  let text$1 = k.add([
    k.pos(x, y),
    k.text(text, {
      size: size
    }),
    k.color(k.Color.fromHex(color)),
    k.anchor(anchor),
    k.area()
  ]);
  if (action !== undefined) {
    text$1.onClick(action);
  }
  if (hoverColor !== undefined) {
    text$1.onHover(() => {
      text$1.color = k.Color.fromHex(hoverColor);
    });
    text$1.onHoverEnd(() => {
      text$1.color = k.Color.fromHex(color);
    });
  }
  return text$1;
}

let Text = {
  make: make
};

function make$1(k, title, menuItems, color, hoverColor) {
  let canvasHeight = k.height();
  let scaleFactor = canvasHeight / 500;
  let centerX = k.width() / 2;
  let topY = k.height() / 4;
  let space = 70 * scaleFactor;
  make(k, title, centerX, topY, "center", color, 36 * scaleFactor, undefined, undefined);
  menuItems.forEach((menuItem, index) => {
    let y = topY + (index + 1 | 0) * space;
    make(k, menuItem.label, centerX, y, "center", color, 24 * scaleFactor, menuItem.action, Stdlib_Option.flatMap(menuItem.action, param => hoverColor));
  });
}

export {
  Text,
  make$1 as make,
}
/*  Not a pure module */
