// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Kaplay from "@nojaf/rescript-kaplay/src/Kaplay.res.mjs";
import * as KaplayContext from "./KaplayContext.res.mjs";

Kaplay.RectComp({});

Kaplay.OutlineComp({});

Kaplay.TileComp({});

function make() {
  return [
    KaplayContext.k.rect(64, 64),
    KaplayContext.k.tile(),
    KaplayContext.k.outline(1, KaplayContext.k.Color.fromHex("#000000"))
  ];
}

let EmptyTile = {
  make: make
};

Kaplay.RectComp({});

Kaplay.OutlineComp({});

Kaplay.ColorComp({});

Kaplay.TileComp({});

function make$1() {
  return [
    KaplayContext.k.rect(64, 64),
    KaplayContext.k.tile(),
    KaplayContext.k.outline(1, KaplayContext.k.Color.fromHex("#0AC0B0"), 1),
    KaplayContext.k.color(KaplayContext.k.Color.fromHex("#00EE00"))
  ];
}

let WallTile = {
  make: make$1
};

Kaplay.SpriteComp({});

Kaplay.TileComp({});

Kaplay.ColorComp({});

Kaplay.AnchorComp({});

Kaplay.PosComp({});

function make$2() {
  return [
    KaplayContext.k.tile(),
    KaplayContext.k.sprite("squirtle", {
      width: 64,
      height: 64
    }),
    KaplayContext.k.color(KaplayContext.k.Color.fromHex("#ADD8E6")),
    KaplayContext.k.anchor("center"),
    KaplayContext.k.pos(64 / 2, 64 / 2),
    "squirtle"
  ];
}

let SquirtleTile = {
  make: make$2
};

Kaplay.SpriteComp({});

Kaplay.TileComp({});

Kaplay.AnchorComp({});

Kaplay.PosComp({});

Kaplay.AgentComp({});

Kaplay.ColorComp({});

function make$3() {
  return [
    KaplayContext.k.sprite("charmander", {
      width: 64,
      height: 64
    }),
    KaplayContext.k.anchor("center"),
    KaplayContext.k.pos(64 / 2, 64 / 2),
    KaplayContext.k.tile(),
    KaplayContext.k.color(KaplayContext.k.Color.fromHex("#FF746C")),
    KaplayContext.k.agent({
      speed: 120,
      allowDiagonals: false
    })
  ];
}

let CharmanderTile = {
  make: make$3
};

function scene() {
  KaplayContext.k.loadSprite("squirtle", "/sprites/squirtle-rb.png");
  KaplayContext.k.loadSprite("charmander", "/sprites/charmander-rb.png");
  KaplayContext.k.loadMusic("beast-in-black", "sounds/beast-in-black.mp3");
  let level = KaplayContext.k.addLevel([
    "##########",
    "#        #",
    "#        #",
    "#        #",
    "##########"
  ], {
    tileWidth: 64,
    tileHeight: 64,
    tiles: {
      " ": make,
      "#": make$1
    }
  });
  let squirtle = level.spawn(make$2(), KaplayContext.k.vec2(1, 1));
  let charmander = level.spawn(make$3(), KaplayContext.k.vec2(7, 4));
  KaplayContext.k.onKeyPress(key => {
    if (key !== "space") {
      return;
    }
    let target = squirtle.pos;
    charmander.setTarget(target);
    KaplayContext.k.play("beast-in-black");
  });
}

let tileSize = 64;

export {
  tileSize,
  EmptyTile,
  WallTile,
  SquirtleTile,
  CharmanderTile,
  scene,
}
/*  Not a pure module */
