// Generated by ReScript, PLEASE EDIT WITH CARE


let attackInCenterOfEnemy = "attackInCenterOfEnemy";

let attackOnTheLeftOfEnemy = "attackOnTheLeftOfEnemy";

let attackOnTheRightOfEnemy = "attackOnTheRightOfEnemy";

let hasSpaceOnTheLeft = "hasSpaceOnTheLeft";

let hasSpaceOnTheRight = "hasSpaceOnTheRight";

let isPlayerLeft = "isPlayerLeft";

let isPlayerRight = "isPlayerRight";

let leftThreat = "leftThreat";

let rightThreat = "rightThreat";

let preferredDodgeLeft = "preferredDodgeLeft";

let preferredDodgeRight = "preferredDodgeRight";

let shouldAttack = "shouldAttack";

export {
  attackInCenterOfEnemy,
  attackOnTheLeftOfEnemy,
  attackOnTheRightOfEnemy,
  hasSpaceOnTheLeft,
  hasSpaceOnTheRight,
  isPlayerLeft,
  isPlayerRight,
  leftThreat,
  rightThreat,
  preferredDodgeLeft,
  preferredDodgeRight,
  shouldAttack,
}
/* No side effect */
