// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AIFacts$Skirmish from "./AIFacts.res.mjs";

function addRules(rs) {
  rs.addRuleExecutingAction(rs => {
    let leftThreat = rs.gradeForFact(AIFacts$Skirmish.leftThreat);
    let rightThreat = rs.gradeForFact(AIFacts$Skirmish.rightThreat);
    if (leftThreat > 0.0) {
      return true;
    } else {
      return rightThreat > 0.0;
    }
  }, rs => {
    let leftThreat = rs.gradeForFact(AIFacts$Skirmish.leftThreat);
    let rightThreat = rs.gradeForFact(AIFacts$Skirmish.rightThreat);
    let leftSpace = rs.gradeForFact(AIFacts$Skirmish.hasSpaceOnTheLeft);
    let rightSpace = rs.gradeForFact(AIFacts$Skirmish.hasSpaceOnTheRight);
    if (leftThreat > rightThreat) {
      rs.assertFact(AIFacts$Skirmish.preferredDodgeRight, 1.0);
    } else if (rightThreat > leftThreat) {
      rs.assertFact(AIFacts$Skirmish.preferredDodgeLeft, 1.0);
    } else if (leftSpace > rightSpace) {
      rs.assertFact(AIFacts$Skirmish.preferredDodgeLeft, 1.0);
    } else {
      rs.assertFact(AIFacts$Skirmish.preferredDodgeRight, 1.0);
    }
  }, 20.0);
  rs.addRuleExecutingAction(rs => {
    let c = rs.gradeForFact(AIFacts$Skirmish.attackInCenterOfEnemy);
    return c > 0.0;
  }, rs => {
    let preferLeft = rs.gradeForFact(AIFacts$Skirmish.preferredDodgeLeft);
    let preferRight = rs.gradeForFact(AIFacts$Skirmish.preferredDodgeRight);
    let leftSpace = rs.gradeForFact(AIFacts$Skirmish.hasSpaceOnTheLeft);
    let rightSpace = rs.gradeForFact(AIFacts$Skirmish.hasSpaceOnTheRight);
    let preferredDirection = preferLeft > 0.0 ? true : (
        preferRight > 0.0 ? false : leftSpace > rightSpace
      );
    let hasSpaceInPreferred;
    hasSpaceInPreferred = preferredDirection === true ? leftSpace > 0.0 : rightSpace > 0.0;
    let finalDirection = hasSpaceInPreferred ? preferredDirection : (
        preferredDirection === true ? rightSpace <= 0.0 : leftSpace > 0.0
      );
    let leftThreat = rs.gradeForFact(AIFacts$Skirmish.leftThreat);
    let rightThreat = rs.gradeForFact(AIFacts$Skirmish.rightThreat);
    let threatsAreEqual = leftThreat === rightThreat && leftThreat > 0.0;
    let currentDirection = rs.state.horizontalMovement;
    if (currentDirection !== undefined && (threatsAreEqual || currentDirection === finalDirection)) {
      return;
    } else {
      rs.state.horizontalMovement = finalDirection;
      return;
    }
  }, 20.0);
  rs.addRuleExecutingAction(rs => {
    let c = rs.gradeForFact(AIFacts$Skirmish.attackInCenterOfEnemy);
    return c === 0.0;
  }, rs => {
    rs.state.horizontalMovement = undefined;
  }, 20.0);
  rs.addRuleExecutingAction(rs => rs.state.playerAttacks.length === 0, rs => {
    let playerLeft = rs.gradeForFact(AIFacts$Skirmish.isPlayerLeft);
    let playerRight = rs.gradeForFact(AIFacts$Skirmish.isPlayerRight);
    let leftSpace = rs.gradeForFact(AIFacts$Skirmish.hasSpaceOnTheLeft);
    let rightSpace = rs.gradeForFact(AIFacts$Skirmish.hasSpaceOnTheRight);
    if (playerLeft > 0.0) {
      rs.state.horizontalMovement = leftSpace > 0.0 ? true : undefined;
    } else if (playerRight > 0.0) {
      rs.state.horizontalMovement = rightSpace > 0.0 ? false : undefined;
    } else {
      rs.state.horizontalMovement = undefined;
    }
  }, 20.0);
}

let salience = 20.0;

export {
  salience,
  addRules,
}
/* No side effect */
