// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AIFacts$Skirmish from "./AIFacts.res.mjs";

function addRules(rs) {
  rs.addRuleExecutingAction(rs => {
    let centerAttack = rs.gradeForFact(AIFacts$Skirmish.attackInCenterOfEnemy);
    let leftAttack = rs.gradeForFact(AIFacts$Skirmish.attackOnTheLeftOfEnemy);
    let rightAttack = rs.gradeForFact(AIFacts$Skirmish.attackOnTheRightOfEnemy);
    if (centerAttack > 0.0 || leftAttack > 0.0) {
      return true;
    } else {
      return rightAttack > 0.0;
    }
  }, rs => {
    let centerAttack = rs.gradeForFact(AIFacts$Skirmish.attackInCenterOfEnemy);
    let leftAttack = rs.gradeForFact(AIFacts$Skirmish.attackOnTheLeftOfEnemy);
    let rightAttack = rs.gradeForFact(AIFacts$Skirmish.attackOnTheRightOfEnemy);
    let leftThreatGrade = leftAttack + centerAttack;
    let rightThreatGrade = rightAttack + centerAttack;
    if (leftThreatGrade > 0.0) {
      rs.assertFact(AIFacts$Skirmish.leftThreat, leftThreatGrade);
    }
    if (rightThreatGrade > 0.0) {
      rs.assertFact(AIFacts$Skirmish.rightThreat, rightThreatGrade);
      return;
    }
  }, 10.0);
}

let salience = 10.0;

export {
  salience,
  addRules,
}
/* No side effect */
