// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.mjs";
import * as PkmnMove$Skirmish from "../PkmnMove.res.mjs";

function addRules(k, rs) {
  let enemy = rs.state.enemy;
  PkmnMove$Skirmish.defaultAddRulesForAI(k, rs, enemy.moveSlot1, PkmnMove$Skirmish.move0Facts);
  PkmnMove$Skirmish.defaultAddRulesForAI(k, rs, enemy.moveSlot2, PkmnMove$Skirmish.move1Facts);
  PkmnMove$Skirmish.defaultAddRulesForAI(k, rs, enemy.moveSlot3, PkmnMove$Skirmish.move2Facts);
  PkmnMove$Skirmish.defaultAddRulesForAI(k, rs, enemy.moveSlot4, PkmnMove$Skirmish.move3Facts);
  enemy.moveSlot1.move.addRulesForAI(k, rs, enemy.moveSlot1, PkmnMove$Skirmish.move0Facts);
  enemy.moveSlot2.move.addRulesForAI(k, rs, enemy.moveSlot2, PkmnMove$Skirmish.move1Facts);
  enemy.moveSlot3.move.addRulesForAI(k, rs, enemy.moveSlot3, PkmnMove$Skirmish.move2Facts);
  enemy.moveSlot4.move.addRulesForAI(k, rs, enemy.moveSlot4, PkmnMove$Skirmish.move3Facts);
}

function selectMove(rs) {
  let moveFacts = [
    PkmnMove$Skirmish.move0Facts,
    PkmnMove$Skirmish.move1Facts,
    PkmnMove$Skirmish.move2Facts,
    PkmnMove$Skirmish.move3Facts
  ];
  return Stdlib_Array.filterMapWithIndex(moveFacts, (facts, index) => {
      let grade = rs.gradeForFact(facts.available);
      if (grade > 0.0) {
        return index;
      }
    })[0];
}

export {
  addRules,
  selectMove,
}
/* No side effect */
