// Generated by ReScript, PLEASE EDIT WITH CARE

import Kaplay from "kaplay";
import * as Primitive_option from "rescript/lib/es6/Primitive_option.js";

let maybeCanvas = document.getElementById("docs-canvas");

let initOptions = {
  global: false,
  background: "#05df72",
  scale: 1
};

let initOptions$1;

if (maybeCanvas == null) {
  initOptions$1 = initOptions;
} else {
  let newrecord = {...initOptions};
  newrecord.canvas = Primitive_option.some(maybeCanvas);
  initOptions$1 = newrecord;
}

let k = Kaplay(initOptions$1);

let maybeCanvas$1 = (maybeCanvas == null) ? undefined : Primitive_option.some(maybeCanvas);

export {
  maybeCanvas$1 as maybeCanvas,
  initOptions$1 as initOptions,
  k,
}
/* maybeCanvas Not a pure module */
