// Generated by ReScript, PLEASE EDIT WITH CARE

import Kaplay from "kaplay";
import * as Pos$Kaplay from "@nojaf/rescript-kaplay/src/Components/Pos.res.mjs";
import * as Sprite$Kaplay from "@nojaf/rescript-kaplay/src/Components/Sprite.res.mjs";

let k = Kaplay({
  width: 500,
  height: 500,
  background: "#05df72"
});

Sprite$Kaplay.Comp({});

Pos$Kaplay.Comp({});

function make() {
  return k.add([
    k.sprite("bean", {
      width: 50,
      height: 50
    }),
    k.pos(200, 100)
  ]);
}

let Bean = {
  make: make
};

k.loadBean();

let bean = make();

export {
  k,
  Bean,
  bean,
}
/* k Not a pure module */
