// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Squirtle from "./Squirtle.res.mjs";
import * as GameContext from "./GameContext.res.mjs";
import * as MiddleEarth from "./MiddleEarth.res.mjs";
import * as PathFinding from "./PathFinding.res.mjs";

GameContext.k.scene("squirtle", Squirtle.scene);

GameContext.k.scene("middle-earth", MiddleEarth.scene);

GameContext.k.scene("path-finding", PathFinding.scene);

GameContext.k.go("path-finding");

/*  Not a pure module */
