// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tower from "./Tower.res.mjs";
import * as Sentry from "./Sentry.res.mjs";
import * as Squirtle from "./Squirtle.res.mjs";
import * as GameContext from "./GameContext.res.mjs";
import * as MiddleEarth from "./MiddleEarth.res.mjs";
import * as PathFinding from "./PathFinding.res.mjs";

GameContext.k.scene("squirtle", Squirtle.scene);

GameContext.k.scene("middle-earth", MiddleEarth.scene);

GameContext.k.scene("path-finding", PathFinding.scene);

GameContext.k.scene("sentry", Sentry.scene);

GameContext.k.scene("tower", Tower.scene);

GameContext.k.go("tower");

/*  Not a pure module */
