// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pos$Kaplay from "@nojaf/rescript-kaplay/src/Components/Pos.res.mjs";
import * as GameContext from "./GameContext.res.mjs";
import * as Rect$Kaplay from "@nojaf/rescript-kaplay/src/Components/Rect.res.mjs";
import * as Tile$Kaplay from "@nojaf/rescript-kaplay/src/Components/Tile.res.mjs";
import * as Agent$Kaplay from "@nojaf/rescript-kaplay/src/Components/Agent.res.mjs";
import * as Color$Kaplay from "@nojaf/rescript-kaplay/src/Components/Color.res.mjs";
import * as Anchor$Kaplay from "@nojaf/rescript-kaplay/src/Components/Anchor.res.mjs";
import * as Sprite$Kaplay from "@nojaf/rescript-kaplay/src/Components/Sprite.res.mjs";
import * as Outline$Kaplay from "@nojaf/rescript-kaplay/src/Components/Outline.res.mjs";

Rect$Kaplay.Comp({});

Outline$Kaplay.Comp({});

Tile$Kaplay.Comp({});

function make() {
  return [
    GameContext.k.rect(64, 64),
    GameContext.k.tile(),
    GameContext.k.outline(1, GameContext.k.Color.fromHex("#000000"))
  ];
}

let EmptyTile = {
  make: make
};

Rect$Kaplay.Comp({});

Outline$Kaplay.Comp({});

Color$Kaplay.Comp({});

Tile$Kaplay.Comp({});

function make$1() {
  return [
    GameContext.k.rect(64, 64),
    GameContext.k.tile(),
    GameContext.k.outline(1, GameContext.k.Color.fromHex("#0AC0B0"), 1),
    GameContext.k.color(GameContext.k.Color.fromHex("#00EE00"))
  ];
}

let WallTile = {
  make: make$1
};

Sprite$Kaplay.Comp({});

Tile$Kaplay.Comp({});

Color$Kaplay.Comp({});

Anchor$Kaplay.Comp({});

Pos$Kaplay.Comp({});

function make$2() {
  return [
    GameContext.k.tile(),
    GameContext.k.sprite("squirtle", {
      width: 64,
      height: 64
    }),
    GameContext.k.color(GameContext.k.Color.fromHex("#ADD8E6")),
    GameContext.k.anchor("center"),
    GameContext.k.pos(64 / 2, 64 / 2),
    "squirtle"
  ];
}

let SquirtleTile = {
  make: make$2
};

Sprite$Kaplay.Comp({});

Tile$Kaplay.Comp({});

Anchor$Kaplay.Comp({});

Pos$Kaplay.Comp({});

Agent$Kaplay.Comp({});

Color$Kaplay.Comp({});

function make$3() {
  return [
    GameContext.k.sprite("charmander", {
      width: 64,
      height: 64
    }),
    GameContext.k.anchor("center"),
    GameContext.k.pos(64 / 2, 64 / 2),
    GameContext.k.tile(),
    GameContext.k.color(GameContext.k.Color.fromHex("#FF746C")),
    GameContext.k.agent({
      speed: 120,
      allowDiagonals: false
    })
  ];
}

let CharmanderTile = {
  make: make$3
};

function scene() {
  GameContext.k.loadSprite("squirtle", "/sprites/squirtle-rb.png");
  GameContext.k.loadSprite("charmander", "/sprites/charmander-rb.png");
  GameContext.k.loadMusic("beast-in-black", "sounds/beast-in-black.mp3");
  let level = GameContext.k.addLevel([
    "##########",
    "#        #",
    "#        #",
    "#        #",
    "##########"
  ], {
    tileWidth: 64,
    tileHeight: 64,
    tiles: {
      " ": make,
      "#": make$1
    }
  });
  let squirtle = level.spawn(make$2(), GameContext.k.vec2(1, 1));
  let charmander = level.spawn(make$3(), GameContext.k.vec2(7, 4));
  GameContext.k.onKeyPress(key => {
    if (key !== "space") {
      return;
    }
    let target = squirtle.pos;
    charmander.setTarget(target);
    GameContext.k.play("beast-in-black");
  });
}

let tileSize = 64;

export {
  tileSize,
  EmptyTile,
  WallTile,
  SquirtleTile,
  CharmanderTile,
  scene,
}
/*  Not a pure module */
