// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Base from "./aux/Base.res.mjs";
import Kaplay from "kaplay";
import * as Pos$Kaplay from "@nojaf/rescript-kaplay/src/Components/Pos.res.mjs";
import * as Area$Kaplay from "@nojaf/rescript-kaplay/src/Components/Area.res.mjs";
import * as Body$Kaplay from "@nojaf/rescript-kaplay/src/Components/Body.res.mjs";
import * as Rect$Kaplay from "@nojaf/rescript-kaplay/src/Components/Rect.res.mjs";
import * as Text$Kaplay from "@nojaf/rescript-kaplay/src/Components/Text.res.mjs";
import * as Color$Kaplay from "@nojaf/rescript-kaplay/src/Components/Color.res.mjs";
import * as Anchor$Kaplay from "@nojaf/rescript-kaplay/src/Components/Anchor.res.mjs";
import * as Sentry$Kaplay from "@nojaf/rescript-kaplay/src/Components/Sentry.res.mjs";
import * as Sprite$Kaplay from "@nojaf/rescript-kaplay/src/Components/Sprite.res.mjs";
import * as GameObjRaw$Kaplay from "@nojaf/rescript-kaplay/src/Components/GameObjRaw.res.mjs";

let k = Kaplay({
  width: 800,
  height: 400,
  background: "#66CCCC",
  scale: Base.scale,
  crisp: true
});

GameObjRaw$Kaplay.Comp({});

Sprite$Kaplay.Comp({});

Pos$Kaplay.Comp({});

Color$Kaplay.Comp({});

Area$Kaplay.Comp({});

Body$Kaplay.Comp({});

Anchor$Kaplay.Comp({});

function make() {
  return k.add([
    k.sprite("squirtle"),
    k.pos(100, 100),
    k.anchor("center"),
    k.color(k.Color.fromHex("#ADD8E6")),
    k.area(),
    k.body()
  ]);
}

let Squirtle = {
  make: make
};

Sprite$Kaplay.Comp({});

Pos$Kaplay.Comp({});

Color$Kaplay.Comp({});

Anchor$Kaplay.Comp({});

Sentry$Kaplay.Comp({});

function make$1(squirtle) {
  return k.add([
    k.sprite("flareon"),
    k.pos(450, 100),
    k.anchor("center"),
    k.color(k.Color.fromHex("#FF746C")),
    k.sentry([squirtle], {
      direction: k.vec2(0, 0),
      fieldOfView: 45,
      lineOfSight: true,
      checkFrequency: 0.200
    })
  ]);
}

let Flareon = {
  make: make$1
};

Rect$Kaplay.Comp({});

Pos$Kaplay.Comp({});

Color$Kaplay.Comp({});

Area$Kaplay.Comp({});

Body$Kaplay.Comp({});

function make$2() {
  return k.add([
    k.rect(20, 200),
    k.pos(250, 0),
    k.color(k.Color.fromHex("#D1E2F3")),
    k.area(),
    k.body({
      isStatic: true
    })
  ]);
}

let Wall = {
  make: make$2
};

Text$Kaplay.Comp({});

Anchor$Kaplay.Comp({});

Pos$Kaplay.Comp({});

function make$3() {
  return k.add([
    k.text("Use the arrow keys to move underneath Flareon (red) to be spotted", {
      size: 16
    }),
    k.pos(k.width() - 20, k.height() - 20),
    k.anchor("botright")
  ]);
}

let Text = {
  make: make$3
};

function onLoad() {
  let squirtle = make();
  let flareon = make$1(squirtle);
  make$2();
  make$3();
  flareon.onObjectsSpotted(spotted => {
    k.debug.log("Spotted squirtle: " + spotted.length.toString());
  });
  squirtle.onKeyDown(key => {
    switch (key) {
      case "left" :
        squirtle.move(k.vec2(-400, 0));
        return;
      case "right" :
        squirtle.move(k.vec2(400, 0));
        return;
      case "up" :
        squirtle.move(k.vec2(0, -400));
        return;
      case "down" :
        squirtle.move(k.vec2(0, 400));
        return;
      case "space" :
      case "enter" :
        return;
    }
  });
}

k.loadSprite("squirtle", import.meta.env.BASE_URL + "/sprites/squirtle-rb.png");

k.loadSprite("flareon", import.meta.env.BASE_URL + "/sprites/flareon-rb.png");

k.onLoad(onLoad);

export {
  k,
  Squirtle,
  Flareon,
  Wall,
  Text,
  onLoad,
}
/* k Not a pure module */
