// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pos$Kaplay from "@nojaf/rescript-kaplay/src/Components/Pos.res.mjs";
import * as Area$Kaplay from "@nojaf/rescript-kaplay/src/Components/Area.res.mjs";
import * as Body$Kaplay from "@nojaf/rescript-kaplay/src/Components/Body.res.mjs";
import * as GameContext from "./GameContext.res.mjs";
import * as Rect$Kaplay from "@nojaf/rescript-kaplay/src/Components/Rect.res.mjs";
import * as Text$Kaplay from "@nojaf/rescript-kaplay/src/Components/Text.res.mjs";
import * as Color$Kaplay from "@nojaf/rescript-kaplay/src/Components/Color.res.mjs";
import * as Anchor$Kaplay from "@nojaf/rescript-kaplay/src/Components/Anchor.res.mjs";
import * as Sentry$Kaplay from "@nojaf/rescript-kaplay/src/Components/Sentry.res.mjs";
import * as Sprite$Kaplay from "@nojaf/rescript-kaplay/src/Components/Sprite.res.mjs";
import * as GameObjRaw$Kaplay from "@nojaf/rescript-kaplay/src/Components/GameObjRaw.res.mjs";

GameObjRaw$Kaplay.Comp({});

Sprite$Kaplay.Comp({});

Pos$Kaplay.Comp({});

Color$Kaplay.Comp({});

Area$Kaplay.Comp({});

Body$Kaplay.Comp({});

Anchor$Kaplay.Comp({});

function make() {
  return GameContext.k.add([
    GameContext.k.sprite("squirtle"),
    GameContext.k.pos(100, 100),
    GameContext.k.anchor("center"),
    GameContext.k.color(GameContext.k.Color.fromHex("#ADD8E6")),
    GameContext.k.area(),
    GameContext.k.body()
  ]);
}

let Squirtle = {
  make: make
};

Sprite$Kaplay.Comp({});

Pos$Kaplay.Comp({});

Color$Kaplay.Comp({});

Anchor$Kaplay.Comp({});

Sentry$Kaplay.Comp({});

function make$1(squirtle) {
  return GameContext.k.add([
    GameContext.k.sprite("flareon"),
    GameContext.k.pos(400, 400),
    GameContext.k.anchor("center"),
    GameContext.k.color(GameContext.k.Color.fromHex("#FF746C")),
    GameContext.k.sentry([squirtle], {
      direction: GameContext.k.vec2(0, 0),
      fieldOfView: 45,
      lineOfSight: true,
      checkFrequency: 0.200
    })
  ]);
}

let Flareon = {
  make: make$1
};

Rect$Kaplay.Comp({});

Pos$Kaplay.Comp({});

Color$Kaplay.Comp({});

Area$Kaplay.Comp({});

Body$Kaplay.Comp({});

Anchor$Kaplay.Comp({});

function make$2() {
  return GameContext.k.add([
    GameContext.k.rect(20, 700),
    GameContext.k.pos(300, 200),
    GameContext.k.anchor("center"),
    GameContext.k.color(GameContext.k.Color.fromHex("#D1E2F3")),
    GameContext.k.area(),
    GameContext.k.body({
      isStatic: true
    })
  ]);
}

let Wall = {
  make: make$2
};

Text$Kaplay.Comp({});

Anchor$Kaplay.Comp({});

Pos$Kaplay.Comp({});

function make$3() {
  return GameContext.k.add([
    GameContext.k.text("Move underneath Flareon (red) to be spotted", {
      size: 20
    }),
    GameContext.k.pos(GameContext.k.width() - 20, GameContext.k.height() - 20),
    GameContext.k.anchor("botright")
  ]);
}

let Text = {
  make: make$3
};

function scene() {
  GameContext.k.loadSprite("squirtle", "sprites/squirtle-rb.png");
  GameContext.k.loadSprite("flareon", "sprites/flareon-rb.png");
  let squirtle = make();
  let flareon = make$1(squirtle);
  make$2();
  make$3();
  flareon.onObjectsSpotted(spotted => {
    GameContext.k.debug.log("Spotted squirtle: " + spotted.length.toString());
  });
  squirtle.onKeyDown(key => {
    switch (key) {
      case "left" :
        squirtle.move(GameContext.k.vec2(-400, 0));
        return;
      case "right" :
        squirtle.move(GameContext.k.vec2(400, 0));
        return;
      case "up" :
        squirtle.move(GameContext.k.vec2(0, -400));
        return;
      case "down" :
        squirtle.move(GameContext.k.vec2(0, 400));
        return;
      case "space" :
      case "enter" :
        return;
    }
  });
}

export {
  Squirtle,
  Flareon,
  Wall,
  Text,
  scene,
}
/*  Not a pure module */
