// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pos$Kaplay from "@nojaf/rescript-kaplay/src/Components/Pos.res.mjs";
import * as Area$Kaplay from "@nojaf/rescript-kaplay/src/Components/Area.res.mjs";
import * as Body$Kaplay from "@nojaf/rescript-kaplay/src/Components/Body.res.mjs";
import * as GameContext from "./GameContext.res.mjs";
import * as Rect$Kaplay from "@nojaf/rescript-kaplay/src/Components/Rect.res.mjs";
import * as Color$Kaplay from "@nojaf/rescript-kaplay/src/Components/Color.res.mjs";
import * as Primitive_int from "rescript/lib/es6/Primitive_int.js";
import * as Sprite$Kaplay from "@nojaf/rescript-kaplay/src/Components/Sprite.res.mjs";

Pos$Kaplay.Comp({});

Sprite$Kaplay.Comp({});

Area$Kaplay.Comp({});

Body$Kaplay.Comp({});

function make(x, y) {
  return GameContext.k.add([
    GameContext.k.pos(x, y),
    GameContext.k.sprite("squirtle", {
      anim: "idle"
    }),
    GameContext.k.area(),
    GameContext.k.body(),
    "squirtle"
  ]);
}

let Squirtle = {
  make: make
};

Pos$Kaplay.Comp({});

Area$Kaplay.Comp({});

Rect$Kaplay.Comp({});

Color$Kaplay.Comp({});

Body$Kaplay.Comp({});

function make$1() {
  return GameContext.k.add([
    GameContext.k.pos(0, GameContext.k.height() - 24),
    GameContext.k.rect(GameContext.k.width(), 24),
    GameContext.k.color(GameContext.k.Color.fromHex("#D97744")),
    GameContext.k.area(),
    GameContext.k.body({
      isStatic: true
    })
  ]);
}

let Ground = {
  make: make$1
};

function scene() {
  GameContext.k.setGravity(250);
  GameContext.k.debug.inspect = true;
  let squirtleSpritesheetDimensions = {
    width: 167,
    height: 39
  };
  let mkSquirtleQuad = (x, y, w, h) => GameContext.k.quad(x / squirtleSpritesheetDimensions.width, y / squirtleSpritesheetDimensions.height, w / squirtleSpritesheetDimensions.width, h / squirtleSpritesheetDimensions.height);
  GameContext.k.loadSprite("squirtle", "sprites/squirtle.png", {
    anims: {
      idle: {
        frames: [0]
      },
      walk: {
        loop: true,
        speed: 12,
        frames: [
          1,
          2,
          3,
          2
        ]
      },
      jump: {
        loop: false,
        frames: [4]
      }
    },
    frames: [
      mkSquirtleQuad(0, 0, 34, 39),
      mkSquirtleQuad(35, 1, 33, 37),
      mkSquirtleQuad(70, 0, 32, 38),
      mkSquirtleQuad(104, 1, 32, 36),
      mkSquirtleQuad(137, 0, 30, 39)
    ]
  });
  make$1();
  let squirtle = make(200, 90);
  GameContext.k.debug.log(squirtle.numFrames().toString());
  squirtle.play("idle");
  GameContext.k.onKeyPress(key => {
    if (squirtle.isGrounded()) {
      switch (key) {
        case "left" :
          squirtle.play("walk");
          squirtle.flipX = false;
          return;
        case "right" :
          squirtle.play("walk");
          squirtle.flipX = true;
          return;
        case "space" :
          squirtle.play("jump");
          squirtle.jump(222);
          return;
        default:
          return;
      }
    } else {
      switch (key) {
        case "left" :
          squirtle.flipX = false;
          return;
        case "right" :
          squirtle.flipX = true;
          return;
        default:
          return;
      }
    }
  });
  GameContext.k.onKeyDown(key => {
    switch (key) {
      case "left" :
        squirtle.move(GameContext.k.vec2(- 200, 0));
        return;
      case "right" :
        squirtle.move(GameContext.k.vec2(200, 0));
        return;
      default:
        return;
    }
  });
  GameContext.k.onKeyRelease(key => {
    switch (key) {
      case "left" :
      case "right" :
        break;
      default:
        return;
    }
    if (squirtle.isGrounded()) {
      squirtle.play("idle");
      return;
    }
    
  });
  squirtle.onGround(() => {
    if (GameContext.k.isKeyDown("left") || GameContext.k.isKeyDown("right")) {
      squirtle.play("walk");
    } else {
      squirtle.play("idle");
    }
  });
  GameContext.k.onClick("squirtle", squirtle => {
    let current = squirtle.frame;
    let max = squirtle.numFrames();
    squirtle.frame = Primitive_int.mod_(current + 1 | 0, max);
  });
}

let x = 799;

export {
  Squirtle,
  Ground,
  scene,
  x,
}
/*  Not a pure module */
