// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PixiJs from "pixi.js";

function addBunny(app) {
  let bunny = PixiJs.Sprite.from("bunny");
  bunny.anchor.set(0.5);
  bunny.x = app.screen.width / 2;
  bunny.y = app.screen.height / 2;
  app.stage.addChild(bunny);
  return bunny;
}

export {
  addBunny,
}
/* pixi.js Not a pure module */
