// Generated by ReScript, PLEASE EDIT WITH CARE

import Kaplay from "kaplay";

let k = Kaplay({
  width: 720,
  height: 320,
  global: false,
  background: "#6495ED",
  scale: 1,
  letterbox: true
});

export {
  k,
}
/* k Not a pure module */
