// Generated by ReScript, PLEASE EDIT WITH CARE


let Debug = {};

let Vec2 = {};

let Shape = {};

let $$Math = {
  Shape: Shape
};

let mathRect = (function (k, pos, width, height) {
    return new k.Rect(pos, width, height);
});

let GameObj = {};

export {
  Debug,
  Vec2,
  $$Math,
  mathRect,
  GameObj,
}
/* No side effect */
