// Generated by ReScript, PLEASE EDIT WITH CARE

import Kaplay from "kaplay";

let screen = {
  width: 720,
  height: 280
};

let k = Kaplay({
  width: screen.width,
  height: screen.height,
  global: false,
  background: "#6495ED",
  scale: 1
});

export {
  screen,
  k,
}
/* k Not a pure module */
