// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Rxjs from "rxjs";

let keydown = Rxjs.fromEvent(window, "keydown").pipe(Rxjs.map(event => ({
  TAG: "Down",
  _0: event.key
})), Rxjs.distinctUntilChanged());

let keyup = Rxjs.fromEvent(window, "keyup").pipe(Rxjs.map(event => ({
  TAG: "Up",
  _0: event.key
})), Rxjs.distinctUntilChanged());

let keyMapObservable = Rxjs.merge(keydown, keyup).pipe(Rxjs.scan((keys, ev) => {
  if (ev.TAG === "Up") {
    keys.delete(ev._0);
    return keys;
  }
  keys.add(ev._0);
  return keys;
}, new Set()));

export {
  keyMapObservable,
}
/* keydown Not a pure module */
