// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tower from "./Tower.res.mjs";
import * as Sentry from "./Sentry.res.mjs";
import * as Squartle from "./Squartle.res.mjs";
import * as MiddleEarth from "./MiddleEarth.res.mjs";
import * as PathFinding from "./PathFinding.res.mjs";
import * as KaplayContext from "./KaplayContext.res.mjs";

KaplayContext.k.scene("squartle", Squartle.scene);

KaplayContext.k.scene("middle-earth", MiddleEarth.scene);

KaplayContext.k.scene("path-finding", PathFinding.scene);

KaplayContext.k.scene("sentry", Sentry.scene);

KaplayContext.k.scene("tower", Tower.scene);

KaplayContext.k.go("tower");

/*  Not a pure module */
