// Generated by ReScript, PLEASE EDIT WITH CARE

import * as KaplayContext from "./KaplayContext.res.mjs";

let gameWidth = KaplayContext.k.width();

let gameHeight = KaplayContext.k.height();

let cameraBounds = {
  x: {
    min: gameWidth / 2 | 0,
    max: 1000 - (gameWidth / 2 | 0) | 0
  },
  y: {
    min: gameHeight / 2 | 0,
    max: 563 - (gameHeight / 2 | 0) | 0
  }
};

function scene() {
  KaplayContext.k.loadSprite("bg", "middle-earth.webp");
  let map = KaplayContext.k.add([
    KaplayContext.k.pos(0, 0),
    KaplayContext.k.sprite("bg", {
      width: 1000,
      height: 563
    }),
    KaplayContext.k.area()
  ]);
  return map.onKeyDown(key => {
    let currentCamPos = KaplayContext.k.getCamPos();
    let move;
    switch (key) {
      case "left" :
        move = KaplayContext.k.vec2(-10, 0);
        break;
      case "right" :
        move = KaplayContext.k.vec2(10, 0);
        break;
      case "up" :
        move = KaplayContext.k.vec2(0, -10);
        break;
      case "down" :
        move = KaplayContext.k.vec2(0, 10);
        break;
      case "space" :
      case "enter" :
        move = KaplayContext.k.vec2(0, 0);
        break;
    }
    let result = currentCamPos.add(move);
    result.x = KaplayContext.k.clamp(result.x, cameraBounds.x.min, cameraBounds.x.max);
    result.y = KaplayContext.k.clamp(result.y, cameraBounds.y.min, cameraBounds.y.max);
    KaplayContext.k.setCamPos(result);
  });
}

let speed = 10;

let mapWidth = 1000;

let mapHeight = 563;

export {
  speed,
  mapWidth,
  mapHeight,
  gameWidth,
  gameHeight,
  cameraBounds,
  scene,
}
/* gameWidth Not a pure module */
