// Generated by ReScript, PLEASE EDIT WITH CARE

import * as KaplayContext from "./KaplayContext.res.mjs";

function scene() {
  KaplayContext.k.loadSprite("squirtle", "/sprites/squirtle-rb.png");
  KaplayContext.k.loadSprite("charmander", "/sprites/charmander-rb.png");
  KaplayContext.k.loadMusic("beast-in-black", "sounds/beast-in-black.mp3");
  let level = KaplayContext.k.addLevel([
    "##########",
    "#  S     #",
    "#        #",
    "#        #",
    "##########"
  ], {
    tileWidth: 64,
    tileHeight: 64,
    tiles: {
      " ": () => [
        KaplayContext.k.rect(64, 64),
        KaplayContext.k.outline(1, KaplayContext.k.Color.fromHex("#000000")),
        KaplayContext.k.opacity(1)
      ],
      "#": () => [
        KaplayContext.k.rect(64, 64),
        KaplayContext.k.tile(),
        KaplayContext.k.color(KaplayContext.k.Color.fromHex("#00EE00")),
        KaplayContext.k.outline(2, KaplayContext.k.Color.fromHex("#0AC0B0"), 1)
      ],
      S: () => [
        KaplayContext.k.tile(),
        KaplayContext.k.sprite("squirtle", {
          width: 64,
          height: 64
        }),
        KaplayContext.k.pos(64 / 2, 64 / 2),
        KaplayContext.k.anchor("center"),
        KaplayContext.k.color(KaplayContext.k.Color.fromHex("#ADD8E6")),
        "squirtle"
      ]
    }
  });
  let charmander = level.spawn([
    KaplayContext.k.sprite("charmander", {
      width: 64,
      height: 64
    }),
    KaplayContext.k.anchor("center"),
    KaplayContext.k.pos(64 / 2, 64 / 2),
    KaplayContext.k.tile(),
    KaplayContext.k.color(KaplayContext.k.Color.fromHex("#FF746C")),
    KaplayContext.k.agent({
      speed: 120,
      allowDiagonals: false
    })
  ], KaplayContext.k.vec2(7, 4));
  KaplayContext.k.onKeyPress(key => {
    if (key !== "space") {
      return;
    }
    let squartle = KaplayContext.k.get("squirtle", {
        recursive: true
      })[0];
    if (squartle !== undefined) {
      let target = squartle.pos;
      charmander.setTarget(target);
      KaplayContext.k.play("beast-in-black");
      return;
    }
    KaplayContext.k.debug.log("No squirtle found");
  });
}

export {
  scene,
}
/* KaplayContext Not a pure module */
