// Generated by ReScript, PLEASE EDIT WITH CARE

import * as KaplayContext from "./KaplayContext.res.mjs";

function scene() {
  KaplayContext.k.loadSprite("squirtle", "/sprites/squirtle-rb.png");
  KaplayContext.k.loadSprite("flareon", "/sprites/flareon-rb.png");
  let squirtle = KaplayContext.k.add([
    KaplayContext.k.sprite("squirtle"),
    KaplayContext.k.pos(100, 100),
    KaplayContext.k.anchor("center"),
    KaplayContext.k.color(KaplayContext.k.Color.fromHex("#ADD8E6")),
    KaplayContext.k.area(),
    KaplayContext.k.body()
  ]);
  let flareon = KaplayContext.k.add([
    KaplayContext.k.sprite("flareon"),
    KaplayContext.k.pos(400, 400),
    KaplayContext.k.anchor("center"),
    KaplayContext.k.color(KaplayContext.k.Color.fromHex("#FF746C")),
    KaplayContext.k.sentry([squirtle], {
      direction: KaplayContext.k.vec2(0, 0),
      fieldOfView: 45,
      lineOfSight: true,
      checkFrequency: 0.200
    })
  ]);
  KaplayContext.k.add([
    KaplayContext.k.rect(20, 700),
    KaplayContext.k.pos(300, 200),
    KaplayContext.k.anchor("center"),
    KaplayContext.k.color(KaplayContext.k.Color.fromHex("#D1E2F3")),
    KaplayContext.k.area(),
    KaplayContext.k.body({
      isStatic: true
    })
  ]);
  KaplayContext.k.add([
    KaplayContext.k.pos(340, 460),
    KaplayContext.k.text("Move underneath Flareon to be spotted", {
      size: 20
    })
  ]);
  flareon.onObjectsSpotted(spotted => {
    KaplayContext.k.debug.log("Spotted squirtle: " + spotted.length.toString());
  });
  return squirtle.onKeyDown(key => {
    switch (key) {
      case "left" :
        squirtle.move(-400, 0);
        return;
      case "right" :
        squirtle.move(400, 0);
        return;
      case "up" :
        squirtle.move(0, -400);
        return;
      case "down" :
        squirtle.move(0, 400);
        return;
      case "space" :
      case "enter" :
        return;
    }
  });
}

export {
  scene,
}
/* KaplayContext Not a pure module */
