// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PixiJs from "pixi.js";

let spritesheet = {
  meta: {
    image: "sprites/squirte-sheet.png",
    format: "RGBA8888",
    size: {
      w: 398,
      h: 311
    },
    scale: 1
  },
  frames: {
    rest: {
      frame: {
        x: 8,
        y: 8,
        w: 34,
        h: 38
      },
      sourceSize: {
        w: 34,
        h: 38
      },
      spriteSourceSize: {
        x: 8,
        y: 8,
        w: 34,
        h: 38
      }
    }
  }
};

async function make(app) {
  let texture = PixiJs.Texture.from(spritesheet.meta.image);
  let spriteSheet = new PixiJs.Spritesheet(texture, spritesheet);
  await spriteSheet.parse();
  let squirtle = new PixiJs.Sprite(spriteSheet.textures["rest"]);
  squirtle.anchor.set(0.5);
  squirtle.x = app.screen.width / 2;
  squirtle.y = app.screen.height / 2;
  app.stage.addChild(squirtle);
  return squirtle;
}

export {
  spritesheet,
  make,
}
/* pixi.js Not a pure module */
