// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Kaplay from "./Kaplay.res.mjs";
import * as Stdlib_Array from "rescript/lib/es6/Stdlib_Array.js";
import * as KaplayContext from "./KaplayContext.res.mjs";
import * as Stdlib_Option from "rescript/lib/es6/Stdlib_Option.js";
import * as Primitive_option from "rescript/lib/es6/Primitive_option.js";

function homing(speed, strength, from, target, timer, maxDistance) {
  let state = {
    velocity: target.pos.sub(from).unit().scale(speed),
    timer: timer
  };
  return {
    id: "homing",
    update: function () {
      let self = this ;
      if (state.timer > 0) {
        let toTarget = target.pos.sub(self.pos).unit();
        state.velocity = state.velocity.lerp(toTarget.scale(speed), strength);
        state.timer = state.timer - KaplayContext.k.dt();
      }
      self.move(state.velocity);
      if (self.pos.dist(from) >= maxDistance) {
        self.destroy();
        return;
      }
      
    }
  };
}

let Homing = {
  homing: homing
};

let bubbleColors = [
  KaplayContext.k.Color.fromHex("#00bcff"),
  KaplayContext.k.Color.fromHex("#a2f4fd"),
  KaplayContext.k.Color.fromHex("#155dfc")
];

let bulletSpeed = KaplayContext.k.vec2(200, 200);

function fireHomingBullet(from, target, maxDistance) {
  let bulletColor = bubbleColors[KaplayContext.k.randi(0, 2)];
  let bullet = KaplayContext.k.add([
    KaplayContext.k.pos(from),
    KaplayContext.k.area(),
    "bullet",
    KaplayContext.k.z(0),
    KaplayContext.k.circle(5, {
      fill: true
    }),
    KaplayContext.k.color(bulletColor),
    homing(bulletSpeed, 0.1, from, target, 0.5, maxDistance)
  ]);
  bullet.onCollide("enemy", (pkmn, param) => {
    bullet.destroy();
    pkmn.hurt(1);
    Stdlib_Option.forEach(pkmn.get("solid-heart").at(0), heart => {
      heart.play("empty");
      heart.untag("solid-heart");
    });
  });
}

function shoot(from, maxDistance) {
  let state = {
    coolDown: 0.3,
    inSight: new Map(),
    loopController: undefined
  };
  return {
    id: "shooting",
    add: function () {
      let self = this ;
      self.onCollide("enemy", (e, param) => {
        state.inSight.set(e.id, e);
      });
      self.onCollideEnd("enemy", e => {
        state.inSight.delete(e.id);
      });
      state.loopController = KaplayContext.k.loop(state.coolDown, () => {
        let next = state.inSight.values().next();
        Stdlib_Option.forEach(next.value, enemy => fireHomingBullet(from, enemy, maxDistance));
      });
    },
    destroy: function () {
      Stdlib_Option.forEach(state.loopController, loopController => {
        loopController.cancel();
      });
    }
  };
}

let Shooting = {
  bubbleColors: bubbleColors,
  bulletSpeed: bulletSpeed,
  homingStrength: 0.1,
  fireHomingBullet: fireHomingBullet,
  shoot: shoot
};

function circlePolygon(center, radius, segmentsOpt) {
  let segments = segmentsOpt !== undefined ? segmentsOpt : 32;
  let points = Stdlib_Array.fromInitializer(segments, idx => {
    let theta = idx / segments * 2 * Math.PI;
    return KaplayContext.k.vec2(center.x + Math.cos(theta) * radius, center.y + Math.sin(theta) * radius);
  });
  return Kaplay.mathPolygon(KaplayContext.k, points);
}

function onSceneLoad() {
  KaplayContext.k.add([
    KaplayContext.k.pos(0, 400),
    KaplayContext.k.rect(KaplayContext.k.width(), 100),
    KaplayContext.k.color(KaplayContext.k.Color.fromHex("#D1E2F3"))
  ]);
  let tower = KaplayContext.k.add([
    KaplayContext.k.pos(KaplayContext.k.width() / 2 | 0, 320),
    KaplayContext.k.circle(30, {
      fill: true
    }),
    KaplayContext.k.color(KaplayContext.k.Color.fromHex("#e2e8f0")),
    KaplayContext.k.body(),
    "tower",
    {
      id: "towerGuy",
      add: function () {
        let tower = this ;
        tower.add([
          KaplayContext.k.sprite("squirtle"),
          KaplayContext.k.anchor("center"),
          KaplayContext.k.color(KaplayContext.k.Color.fromHex("#00d3f2")),
          KaplayContext.k.z(10)
        ]);
      }
    }
  ]);
  tower.add([
    KaplayContext.k.circle(200, {
      fill: true
    }),
    KaplayContext.k.color(KaplayContext.k.Color.fromHex("#D1FEB8")),
    KaplayContext.k.opacity(0),
    KaplayContext.k.area({
      shape: Primitive_option.some(circlePolygon(KaplayContext.k.vec2(0, 0), 200, 32))
    }),
    shoot(tower.pos, 200)
  ]);
  let regularColor = KaplayContext.k.Color.fromHex("#fe9441");
  KaplayContext.k.loop(1, () => {
    let charmander = KaplayContext.k.add([
      KaplayContext.k.sprite("charmander", {
        height: 36,
        flipX: true
      }),
      KaplayContext.k.color(regularColor),
      "enemy",
      KaplayContext.k.pos(50, 450),
      KaplayContext.k.area(),
      KaplayContext.k.anchor("center"),
      KaplayContext.k.move(KaplayContext.k.vec2(1, 0), 100),
      KaplayContext.k.offscreen({
        destroy: true
      }),
      KaplayContext.k.health(3),
      {
        id: "hearts",
        add: function () {
          let charmander = this ;
          let hp = charmander.hp();
          for (let i = 1; i <= hp; ++i) {
            charmander.add([
              KaplayContext.k.pos(25 - (i * 15 | 0) | 0, -35),
              KaplayContext.k.sprite("heart", {
                width: 10,
                height: 10
              }),
              "solid-heart"
            ]);
          }
        }
      }
    ]);
    charmander.onDeath(() => {
      KaplayContext.k.destroy(charmander);
    });
  });
}

function scene() {
  KaplayContext.k.loadSprite("charmander", "/sprites/charmander-rb.png");
  KaplayContext.k.loadSprite("squirtle", "/sprites/squirtle-rb.png");
  KaplayContext.k.loadSprite("heart", "/sprites/heart.png", {
    sliceX: 2,
    sliceY: 1,
    anims: {
      solid: {
        from: 0,
        to: 0
      },
      empty: {
        from: 1,
        to: 1
      }
    },
    anim: "solid"
  });
  KaplayContext.k.onLoad(onSceneLoad);
}

export {
  Homing,
  Shooting,
  circlePolygon,
  onSceneLoad,
  scene,
}
/* bubbleColors Not a pure module */
