// Generated by ReScript, PLEASE EDIT WITH CARE

import * as GameObjRaw$Kaplay from "./GameObjRaw.res.mjs";

function Comp(T) {
  GameObjRaw$Kaplay.Comp({});
  return {};
}

export {
  Comp,
}
/* No side effect */
