// Generated by ReScript, PLEASE EDIT WITH CARE


let fromRGB = (function (k, r, g, b) {
    return new k.Color(r,g,b);
});

function Comp(T) {
  return {};
}

export {
  fromRGB,
  Comp,
}
/* No side effect */
