// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.mjs";
import * as GameObjRaw$Kaplay from "./GameObjRaw.res.mjs";

function Comp(T) {
  return {};
}

GameObjRaw$Kaplay.Comp({});

function fromGameObj(obj) {
  if (obj.has("pos")) {
    return Primitive_option.some(obj);
  }
}

let Unit = {
  fromGameObj: fromGameObj
};

export {
  Comp,
  Unit,
}
/*  Not a pure module */
